### ISSUE TITLE
Make the Release Notes task calculate wi and commits like TFS, based on previous Release

### ISSUE THREAD

**Issue by rfennell** [rfennell/vNextBuild#100]
At present the Generate Release Notes task finds a list of builds and checks each one for the wi and commits associated. This does generate the same list when the task is used within a build, but a very different list to that shown for a release.

The is not way to unify the the two, so I have decided to build a second version of the release notes task that make the same REST calls as the VSTS Release Management UI.

I also intend to try to port this to Node (from PowerShell) to see if I cross platform version can be created.

So a bit of a research project

**Comment by saslanov** [comment]
+1 for the item. It would be very useful to have a delta of commits / wi comparing to the previous release, and not just for the build used.

**Comment by rfennell** [comment]
Development is underway of a Node based task that uses the correct REST calls to get the data in the same manner as VSTS shows

**Comment by rfennell** [comment]
Have a look at my nww`[crossplatform extension](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes).

See [this blog post](http://blogs.blackmarble.co.uk/blogs/rfennell/post/2017/04/12/New-Cross-Platform-version-of-my-Generate-Release-Notes-VSTS-Extension) for background
