### ISSUE TITLE
2.6.2 Generate Release Notes question - can I pull System.Description with the condition that the work item is an Epic?

### ISSUE THREAD

**Issue by johnnavarra** [rfennell/vNextBuild#102]
### VSTS Extension you are using
Generate Release Notes

### Where are you running it?
VSTS
### Version of Extension/Task
2.6.2

can I pull System.Description with the condition that the work item is an Epic?

**Comment by rfennell** [comment]
Sorry no, the system does not allow conditional logic. This was a decision made to avoid the possibility of untrusted code being run. 

There is a more detailed discussion in some of the other issues
