### ISSUE TITLE
Generate Release notes Build tasks doesn't appear to show up as an available task

### ISSUE THREAD

**Issue by ploegert** [rfennell/vNextBuild#11]
On release 1.3.22, after adding the extension to my vsts instance, I don't see the option in my build tasks under Utilites or "All Items". Perhaps I'm missing something?

**Comment by rfennell** [comment]
I just retested with a VSTS account that did not have it previously installed, this is the process I used (I assume it is the same as your)

1.  Logged into VSTS instance
2.  When to marketplace, picked the extension, pressed install button and selected my VSTS instance and confirmed installation
3.  On https://<instance>.visualstudio.com/_admin/_apps/hub/ms.vss-extmgmt-web.manageExtensions-collection?tab=Manage&status=active# I could see the generate release note extension
4.  I went to a build and in edit mode and tried to add a new task, the generate release notes task could be found in the 'all' list and the 'utilities' list

So it seems OK to me, but that said, whilst testing last week I did see some propagation delays between publishing a new version and it appearing, so you maybe suffering a similar issue?

**Comment by ploegert** [comment]
Great! Yeah those are the same steps that I followed as well! VSTS was being grumpy yesterday, so maybe there is some lingering infrastructure ickyness still lurking. I'll wait till the morning and see if maybe it pops up! Thx for answering back to quick! This is a pretty awesome extension! I really have a use for it!

**Comment by rfennell** [comment]
Any luck as yet, has the task appeared?

**Comment by jwestes** [comment]
I'm seeing exactly the same behavior.  It is listed as installed but I cannot select it from a build definition.

**Comment by rfennell** [comment]
Jwestes - I am assuming you are on VSTS. Now some time has passed has the task appeared? i.e. is it just slow?

I have others using the task without an issue, so this is strange you two have had this problem.

I am checking with Microsoft to see if there are any known issue that could cause this.

**Comment by Bowman74** [comment]
I am also on VSTS and am encountering the same. It shows up as being installed but never appears in the add task window. I've looked under the "All" category and each individual category.

**Comment by Bowman74** [comment]
For a little more information it doesn't show up when using the default build agent or the VSTS MacInCloud OSX build agent. I have included some screen shots of what the agent capabilities are (if that helps in any way).

<img width="492" alt="screen shot 2016-06-02 at 9 17 46 am" src="https://cloud.githubusercontent.com/assets/4380198/15746137/4454f9d2-28a3-11e6-94a6-e8f354f28878.png">

<img width="488" alt="screen shot 2016-06-02 at 9 18 55 am" src="https://cloud.githubusercontent.com/assets/4380198/15746158/56799366-28a3-11e6-89b5-7cc48961a970.png">

**Comment by rfennell** [comment]
It won't work for a MAC as it is PowerShell based, longer term aim to add Node version but don't have the time at present (there is an issue about this).

Much of my testing has been on the hosted build agent, so it should work there

**Comment by jwestes** [comment]
It has been 24 hours and it is still not showing up.  I am using a Default build agent that is hosted in our company's data center. Could that have anything to do with it?

**Comment by rfennell** [comment]
Can't see why, as when defining the build tasks it has not got anywhere near an agent, it is all server at that point.

I have a call open with MS, see if they have ideas

**Comment by jwestes** [comment]
That's what I thought, but I saw that you said you had been doing your testing with the Hosted build pool so I figured I would mention it.

**Comment by rfennell** [comment]
There are a number of you are suffering this issue with tasks not appearing, I am in discussion with MS to try to work out why. 

If you are suffering the problem could you let me know your VSTS instance name so MS can look into why you don't see the task, either pop them in this thread or email me directly at richard@blackmarble.co.uk

**Comment by rfennell** [comment]
I have just heard back from Microsoft and they think the issue of not seeing a task could be due to do to unfortunate timing of the installation of the extension on when VSTS got updated. They recently changed the mechanism to install extensions and think that may have affected your extension. **Can you please try installing it again** Please let me know if you still face the issue, telling the the VSTS instance name helps with tracing the ussyes

**Comment by jwestes** [comment]
I just removed and reinstalled and I still don't see it in my list of available build steps.  I'll wait a bit and try it again.

Jason Estesjestes@vintagevolks.com

Date: Tue, 7 Jun 2016 09:56:44 -0700

**Comment by rfennell** [comment]
OK I will report that back and keep digging

**Comment by rfennell** [comment]
I have had a similar issue on my test VSTS instance where I test the private builds of my extension. It seems that the issue was a failed install of the task(s), though the extension says it share/installed ok. Another symptom was of you look at the list of extensions installed on your VSTS instance no un-install/disable buttons are shown 

I fixed it by unsharing the private extension and then reinstalling i.e. started again.

For a public extension I think the bets option will be uninstall and try again - sorry I don't have a better answer

**Comment by jwestes** [comment]
I have tried uninstalling and reinstalling once already and it did not work.  I have just uninstalled again and I will leave it until tomorrow before I reinstall.  Just to see if that helps.

**Comment by rfennell** [comment]
I just did a test install on a clean VSTS instance, installed OK, but did take a minute or two appear in the task list

**Comment by jwestes** [comment]
I installed Wednesday and checked this morning before uninstalling and it still was not listed.

**Comment by jwestes** [comment]
I removed it this morning, reinstalled at lunch and waited until bed to check.  It's working!

**Comment by rfennell** [comment]
Great news, hope it lives up to the expectation after all of that !

**Comment by ploegert** [comment]
I'll give it another shot tomorrow.

**Comment by rfennell** [comment]
I will assume this issue is resolved if I don't hear anything in 7 days
