### ISSUE TITLE
The build step Version Dacpac files fails when database project contains references to system databases (msdb or master)

### ISSUE THREAD

**Issue by Radamonas** [rfennell/vNextBuild#111]
### Where are you running it?
On-premise TFS (2015)

### Version of Extension/Task
1.10.1

### Expected behavior and actual behavior
I'd expect to have those referenced dbs to be skipped by the build step.

### Steps to reproduce the problem
Database project which has one or both system databases (msdb or master) added as references and the dacpacs were created for the during the build.
The build step is failing because it is not able to set version to those dacpacs.

**Comment by ChrisLGardner** [comment]
I've just done a fix for this, I'll put in a PR for it now.

**Comment by rfennell** [comment]
Released in 1.14.x
