### ISSUE TITLE
GenerateReleaseNotes - 401 Unauthorized error thrown when using on-premise TFS 2015 Update 2

### ISSUE THREAD

**Issue by sumo300** [rfennell/vNextBuild#12]
We're getting the following error when trying to use this with an on-premise install.

Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (401) Unauthorized."

I've seen this happening a lot with our on-premise install and extensions.  We use SSL and have configured TFS on port 443 only.  We also use an internal CA for our organization.  Not sure if this helps track down the issue.

**Comment by rfennell** [comment]
Can I check my understanding

1. You are saying this extension work some times and sometimes not?
2. Also is it right you have seen similar intermittent behaviour with other extensions?

FYI: The security is managed by reusing the same security token that is active for the build/release. I do nothing except add the token to the header of the request.

**Comment by sumo300** [comment]
1. It does not work at all.  It always fails with the 401 unauthorized.  I have enabled "Allow Scripts to Access OAuth Token" as well.
2. Yes, I have seen similar 401 unauthorized errors with other extensions, but not part of build.
3. This was on build, not release.

I just thought of something, though.  What exactly is in the DownloadString variable as far as the URL is concerned?  I assume it's just one of TFS's URLs  I'm wondering if this is our silly server proxy that does silly things like proxy and block access to its own IPs and addresses thinking they are external.  If it is, smh.

**Comment by sumo300** [comment]
Looking at this further, one of the extensions that is failing is one that shows all active pull request.  The URL it is trying to access is this one, which it gets a 401 unauthorized.  I think this has something to do with configuration, but not sure what as this was a clean install and upgrade of 2013 that we tested first and everything worked just fine.  And, yes, this URL is short.  we have a default domain in our DNS that allows us to do this.

https://tfs/tfs/xxxxxxx/Applications/_apis/git/Repositories?includeLinks=true

**Comment by sumo300** [comment]
More research indicates this may be an issue with how the APIs are called and scopes, not the proxy.

https://freerangeeggs.net/2016/02/11/tfs-webapi-exception-401-in-visual-studio-team-services-extension/

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/e9a0372e-c4aa-43f0-b1fa-479571f7b9b1/vso-extension-calling-rest-api-results-in-tfswebapiexception-401-error?forum=TFService

**Comment by rfennell** [comment]
DownloadString is just a Get call to the REST interface, the argument is the url.

I have just pulled the current version of the tools (that supports build and releases 1.3.x) onto our on prem 2015.2 and retested, which only uses Https, so similar to your setup. It worked OK for me.

To work out which call is failing I need to see the tasks's log from the build, but I suspect it is the first Get which is failing, this is going to be in the form

https://tfs/tfs/xxxxxxx/Applications/_apis/build/builds/<the ID of the active build>?api-version=2.0"

You should be able to copy the URL out of the log and try it in a browser and see the json data set. Not sure how much this will show, which may shed some light

**Comment by rfennell** [comment]
The test build I just did on the edit build > general > build authorisation scope is set to project collection.

What is your setting?

**Comment by sumo300** [comment]
Project Collection is my setting.  I've attached the log with my latest attempt.
[1_Build.txt](https://github.com/rfennell/vNextBuild/files/289833/1_Build.txt)

**Comment by rfennell** [comment]
Yep, as suspected all your GET calls are failing (three in your case, the build, the associated work items and changesets)

I would try running as an agent who has more rights as a test. The strange thing is it is using the same token as the agent itself.

**Comment by sumo300** [comment]
1. First test - Switched to the service account TFS is running under instead of our separate build account.  Failed.
2. Used my own account (I'm one of the TFS Administrators) - Failed.

**Comment by sumo300** [comment]
Note that in your manfiest, I don't see a "scopes" section to allow this API access.

https://www.visualstudio.com/en-us/integrate/extensions/develop/manifest#scopes

**Comment by rfennell** [comment]
What does https://tfs/tfs/XXXXX/Applications/_apis/build/builds/1220?api-version=2.0 return from a browser logged into any of the user accounts your have been testing. Where 1220 is the build ID from your log.

I would expect it to show the build details, the tasks is to doing anything special, just GETs. I worked out the basic logic by hacking around in Chrome with the API to work out what I needed.

**Comment by sumo300** [comment]
Logged in as myself (the user the build agent is currently running as), it displays JSON.

**Comment by rfennell** [comment]
I have not needed to set these, as I have assumed that as I am reusing a token I fall into the option of  'If no scopes are specified, extensions are only provided access to user profile and extension data.'

**Comment by sumo300** [comment]
I think the scopes are now required.  I could be wrong.

**Comment by rfennell** [comment]
That is strange, lets add some and see what happens. I will add some and send your a private build

**Comment by rfennell** [comment]
One question are you on 2015.2 or 2015.2.1? I tested in 2015.2
I have attached a quick test build (1.4.1), the only difference is that I have added the scope.

Now this does cause some issue as once, published you can't alter a scope of if this is the fix I am going to have to think how to republish it.

Let me know now it goes

[richardfennellbm.BM-VSTS-GenerateReleaseNotes-Task-1.4.1.zip](https://github.com/rfennell/vNextBuild/files/289887/richardfennellbm.BM-VSTS-GenerateReleaseNotes-Task-1.4.1.zip)

copes.

**Comment by sumo300** [comment]
Well, there goes that theory.  Still the same 401 unauthorized error.  And, I'm on 2015.2, at least according to the TFS admin (14.95.25122.0 (Tfs2015.Update2)).  I swore I was on 2015.2.1.  I will update to 2015.2.1 and get back to this thread.  I apologize if this ended up being a waste of time.

**Comment by rfennell** [comment]
I have not gone to 2015.2.1 on prem (decided to only apply if we were affected by any of the bugs it fixes, which we have not). So I woukld be surprised if that is be the issue.

It really does look like some form of security trimming issue.

**Comment by rfennell** [comment]
Have you made any progress on this issue?
More logs maybe?

**Comment by sumo300** [comment]
Actually, yes.  On all API calls that return a 401 Unauthorized, the IIS logs show that no user is submitted with the GET request.  All other requests that return valid statuses also have either the service account or the logged in user.

For example, this one is one of the calls from the Release Notes task:

2016-06-21 00:00:49 10.230.31.23 GET /tfs/******/Applications/_git/*****/info/refs service=git-receive-pack 443 - xx.xxx.xx.xxx git/2.8.3.windows.1 - 401 2 5 0

**Comment by rfennell** [comment]
The task should be using the token provided by the current build

`
  $vssEndPoint = Get-ServiceEndPoint -Name "SystemVssConnection" -Context $distributedTaskContext
    $personalAccessToken = $vssEndpoint.Authorization.Parameters.AccessToken
    $webclient = new-object System.Net.WebClient
    $webclient.Headers.Add("Authorization" ,"Bearer $personalAccessToken")
`
I can think of no reason you should be seeing the problems you are having, I have retested again with the 1.3.x version both on VSTS and on our on prem TFS instance (that used SSL). 

It does seem like something is getting in the way between the extension and the TFS server, but not sure where to go next

**Comment by sumo300** [comment]
I agree.  The build is configured to allow access to the OAuth token.  I've tinkered with adding the build account to certain roles for the agent pool, the actual team itself where the repos and work is, etc.

Would it make sense to try to use Fiddler from the build server to see if I could get more details?

**Comment by rfennell** [comment]
Seems a good plan, can't think of much else

**Comment by sumo300** [comment]
Are you using this method to get the OAuth token?

https://www.visualstudio.com/en-us/docs/integrate/get-started/auth/oauth

**Comment by rfennell** [comment]
This is not an external app so I don't need to authorise the APP in that manner, I am running in the agent process. I got the form of the token code from the [MS code for standard VSTS tasks GitHub repo](https://github.com/Microsoft/vsts-tasks/search?utf8=%E2%9C%93&q=SystemVssConnection).

I don't think there is a architectural issue here as I have reports of this task working for many people, and all my test pass on VSTS and TFS

Sorry I can't pinpoint your issue. Can you test on a VSTS instance or a test on prem instance?

**Comment by sumo300** [comment]
Yeah, you're right.  Drawing at straws until I get approval to install Fiddler.

**Comment by SiCro** [comment]
Did you work this one out? Did you enable 'basic authentication' on the TFS Web Site

**Comment by sumo300** [comment]
Actually, I'm thinking this issue can be closed.  We updated to Update 3 on Friday and the extension started working again.  Note that before the upgrade, I removed Basic Authentication as Update 3 adds SSH support, which is all that was needed for non-Windows accounts.  Basic Auth is now disabled and seems to work under Update 3 (which did also update the build agents to a slightly newer version).

**Comment by rfennell** [comment]
I have just released 1.4.7 of the release notes extension. This provides a new advanced options that allows you to switch the authentication model.

The default remains the same i.e. use a personal access token provided by the server, but you have the option to enable use of the 'defaultcredentials' i.e the account the build agent is running as. Hopefully this should fix these 401 issues buy some people when running with on prem TFS
