### ISSUE TITLE
XPlatGenerateReleaseNotes incompatible with multiple artifacts

### ISSUE THREAD

**Issue by gregpakes** [rfennell/vNextBuild#127]
### VSTS Extension you are using
XPlatGenerateReleaseNotes

### Where are you running it?
TFS 2017 Update 1

### Version of Extension/Task
1.1.15

### Expected behavior and actual behavior

The extension doesn't work if you have multiple artifacts and use TFVC source control (I am not sure if it works with git).

It only seems to look at the primary build and then looks for changesets totally unrelated to the build.

**Comment by gregpakes** [comment]
Added PR #130

**Comment by rfennell** [comment]
Released in 1.2.2
