### ISSUE TITLE
Version Field for .NET Core is broken

### ISSUE THREAD

**Issue by zivillian** [rfennell/vNextBuild#129]
### VSTS Extension you are using
Manifest Versioning Build Tasks - VersionDotNetCoreAssemblies

### Where are you running it?
TFS 2017

### Version of Extension/Task
1.15.22

### Expected behavior and actual behavior
When specifying a version field to update the newVersion replacement pattern is build for each matched csproj file. This results in invalid files, since the field name repeated:
```<VersionPrefix><VersionPrefix>1.0.9</VersionPrefix></VersionPrefix>```

### Steps to reproduce the problem
- specify a version field
- have multiple matched files

### Source
The newVersion field is extended in each loop and never reset in [ApplyVersionToAssemblies.ts#L90](https://github.com/rfennell/vNextBuild/blob/97b4bfedc0c86208e73f41ceee91b398dce85db5/Extensions/Versioning/VersionDotNetCoreAssembliesTask.src/ApplyVersionToAssemblies.ts#L90)

**Comment by rfennell** [comment]
Fixed in 1.16.2
