### ISSUE TITLE
Typemock.ps1 contains syntax errors

### ISSUE THREAD

**Issue by RPaardekam** [rfennell/vNextBuild#13]
My builds fail because of basic syntax issues in the Typemock.ps1 script. Maybe this is related to the PowerShell version that I use, compared to the one you have used for your development, but in my case the task simply doesn't work. 

Your code:
`if (!Test-Path($runSettingsFile))`

My code:
`if (!(Test-Path $runSettingsFile))`

This fixed it for me.

**Comment by rfennell** [comment]
I have repo's the problem. Embarrassed to say it was down to poor testing. This code was ported from my C#/XAML build equivalent, for speed I did not bring over all the unit tests to exercise all code paths.

All the more reason to add Pester tests in the future.

I am currently rebuilding and packaging the fix

**Comment by rfennell** [comment]
The revised extension is in the marketplace as version 1.1.1

**Comment by rfennell** [comment]
Did this revised version work for you?

**Comment by rfennell** [comment]
I am closing this as I think it is fixed, reopen if there is still an issue

**Comment by RPaardekam** [comment]
Apologies for not getting back to you earlier Richard. I have moved away
from using your extension and started using the one that Typemock supplied
themselves as I was afraid it would affect the level of support I needed
from the Typemock support-team. The standard task they ship with their
product seems to work pretty well at the moment.

Thanks for assisting me though.

2016-06-06 12:39 GMT+02:00 Richard Fennell <notifications@github.com>:

> I am closing this as I think it is fixed, reopen if there is still an issue
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rfennell/vNextBuild/issues/13#issuecomment-223924355>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASgsH_gWwTv6eZiW4dpS5BuQSYDgMUSAks5qI_jIgaJpZM4IpxlQ>
> .
>



-- 
Met vriendelijke groet,

Robin Paardekam

-- Berichten aan dit adres komen ook direct aan op mijn telefoon. --

**Comment by rfennell** [comment]
That's no problem, I always wrote my task as a stopgap measure when there was no support for TFS vNext build by Typemock.

I would always recommend using the vendor tools (and their support) if they exist, but will aim to keep my task up to date. I think a task is a little easier to use than a PowerShell script
