### ISSUE TITLE
Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (400) Bad Request."

### ISSUE THREAD

**Issue by uioporqwerty** [rfennell/vNextBuild#133]
### VSTS Extension you are using
*There are a number of VSTS extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*
Generate Release Notes Build Task

### Where are you running it?
*VSTS or on-premise TFS (if so what version)*
On-premise TFS 2015

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*
2.9.2

### Expected behavior and actual behavior
Expected Behavior: Release notes are generated

Actual Behavior: Powershell script errors out on trying to fetch information on TFS.

### Steps to reproduce the problem
Run version 2.9.2 of this extension with TFS 2015 and uncheck the option for "Generate for only this Release".

```$allReleases = Get-ReleaseByDefinitionId -tfsUri $collectionUrl -teamproject $teamproject -releasedefid $releasedefid -usedefaultcreds $usedefaultcreds``` is throwing the error above. 

It seems to me that the ```else``` clause uses the above ```Get-ReleaseByDefinitionId``` which has a blank value for ```$releasedefid``` since TFS 2015 Update 2 does not support ```$releasedefid```. I think if ```$releasedefid``` is null or empty we could grab the definitions using ```_apis/release/definitions```, find the definition with the name of ```$releasedefname```, and then populate ```$releasedefid``` with the json id value. If you want, I could code this up unless you think it wouldn't work or propose a better approach :)

**Comment by uioporqwerty** [comment]
I have this fixed using the approach detailed in the last paragraph. Would this suffice? If so, I can submit a small PR soon.

**Comment by uioporqwerty** [comment]
#134

**Comment by rfennell** [comment]
Released in 2.10.2
