### ISSUE TITLE
How to get work item href in XplatGenerateReleaseNotes

### ISSUE THREAD

**Issue by chakaSA** [rfennell/vNextBuild#135]
FYI: Don't think its a bug, just lack of knowledge my side to get the info :(
Info in repo steps

### VSTS Extension you are using
XplatGenerateReleaseNotes

### Where are you running it?
VSTS

### Version of Extension/Task
latest 1.1.5

### Expected behavior and actual behavior
Return work items href to open in edit mode in vsts.

### Steps to reproduce the problem
Not sure how to get the url via the template
Viewing the output of /_apis/wit/workItems/2167 I see the following I'm after
"_links": {
               "html": {
                              "href": "https://xxx/web/wi.aspx?pcguid=f70a9cf7-2ff6-40be-a969-a74687490b0a&id=2167"
                 },
}

I tried the following in the template: ${widetail._links.html.href} and some other combos.

Get the following:
[error]Unhandled: Cannot read property 'html' of undefined
[debug]Processed: ##vso[task.issue type=error;]Unhandled: Cannot read property 'html' of undefined
[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Cannot read property 'html' of undefined

Appreciate any suggestions.
Thx

**Comment by rfennell** [comment]
I think the answer is simple, place this in the template.md file (or inline)

`${widetail.url}
`
This generates 

`* ** Product Backlog Item [13](https://richardfennell.visualstudio.com/_apis/wit/workItems/13) ** Assigned by: Richard Fennell (Work MSA) <bm-richard.fennell@outlook.com>  PBI to link`

So the link url is the _apis link for the work item.

I have checked the code and the 'web view' URL is not available in the data I provide to the template. Basically all that is retrieved is the ID, APIS URl and the fields.

The only option I guess would be to build the url in the form within the template

`https://richardfennell.visualstudio.com/GitHub/_workitems?id=13&_a=edit`

**Comment by rfennell** [comment]
Great glad you are unblocked
