### ISSUE TITLE
Version Nuspec build task is overlooking Nuspec files at root Path folder

### ISSUE THREAD

**Issue by apfinger** [rfennell/vNextBuild#143]
### VSTS Extension you are using
Extension: Manifest Versioning Build Tasks
TFS Build Task: Version Nuspec

### Where are you running it?
on-premise TFS 2017 Update 1 (upgraded from TFS 2015 Update 2)

### Version of Extension/Task
v1.16.2 (upgraded from v1.7.*)

### Expected behavior and actual behavior
Expected behavior:
  After specifying the subfolder "$(Build.SourcesDirectory)/$(Project.Name)/"
  I expected the task to find the nuspec file located in that directory.

Actual Behavior:
  TFS build warning "Found no files."

  The PowerShell script causing this behavior is ?{ $_.PSIsContainer } when setting the $files variable. This is filtering out any nuspec files in the root $Path variable.

### Steps to reproduce the problem
Have a repo: MyRepo
Create a csproj, MyProj, in a subfolder, MySubfolder, of MyRepo
Add a nuspec file to MySubfolder, which should be at the same folder level as the MyProj.csproj file
In the build definition, add the "Version Nuspec" build task
Specify source folder: "$(Build.SourcesDirectory)/MySubfolder"
Specify version number: $(Build.BuildNumber)
Ensure Build.BuildNumber generates a matching regex for the version number
Queue new build
Verify "Found not files." warning from the build log.
Verify the nuspec file does not update in the Build Agent directory

**Comment by ChrisLGardner** [comment]
I've got a fix for this in progress. Just need to finish writing the tests and then I'll get it a PR submitted.
