### ISSUE TITLE
Missing script files from .NET Core Versioning Task

### ISSUE THREAD

**Issue by aidanfolkes** [rfennell/vNextBuild#146]
### VSTS Extension you are using
Version .NET Core Assemblies

### Where are you running it?
VSTS both Private and Hosted VS 2017 build servers

### Version of Extension/Task
1.17.2

### Expected behavior and actual behavior
Expected
.NET Core Assembly version updated.

Actual
Task fails with error message:
File not found: 'd:\a\_tasks\VersionDotNetCoreAssemblies_4578fa22-6039-4d83-90e0-3e12f68d6b26\1.17.2\ApplyVersionToAssemblies.js'

ApplyVersionToAssemblies.js and ApplyVersionToAssemblies.js.map files are not downloaded to build server.

### Steps to reproduce the problem
Use the Version .NET Core Assemblies build task

**Comment by rfennell** [comment]
Strange, I used that control last week on the hosted 2017 controllers and it seemed to work. Let me recheck.

Do you have a private build host you could try it on? So we can see of the files are actually there?

**Comment by johnnybegood** [comment]
Since today we have the same issue on hosted agents (2017). Yesterday it was working.

**Comment by ChrisLGardner** [comment]
Looks like it was probably something I broke when releasing a new build yesterday. I'll try to get it fixed as soon as I can today.

**Comment by rfennell** [comment]
It is an intermittent fault in the build process, on a percentage of builds it fails to save the .js and .js/map files - needs more investigation but have just deployed build 1.18.3 that fixed the immediate issue

**Comment by aidanfolkes** [comment]
Build now works!
Thanks for the quick response.
