### ISSUE TITLE
get the latest commitID/changeset

### ISSUE THREAD

**Issue by shmullikah** [rfennell/vNextBuild#15]
Hi,
how can i add the latest commitid/changeset of the current repo/tfsvc folder?

**Comment by rfennell** [comment]
Can you provide a bit more context?

- Which extension/task are you working with?
- Where do you want to add this latest commitID?

My guess is you are using the Release Notes extension, if that is the case it should all be automatic which changesets are picked up i.e. the ones associated with builds.

If you want different logic then you would need to change the PowerShell in the extension.

An alternative would be to write your own script (that you include as part of the build/release) that updates the generated .MD file after it has been generated

**Comment by rfennell** [comment]
Can you provide more detail, if not I will close the issue in 7 days
