### ISSUE TITLE
After a release downgrade, the detected version to compare seems wrong

### ISSUE THREAD

**Issue by MarcDrexler** [rfennell/vNextBuild#153]
### VSTS Extension you are using
*GenerateReleaseNotes Extension (XPlat)*

### Where are you running it?
*TFS 2017 Update 2*

### Version of Extension/Task
*currently public version*

### Expected behavior and actual behavior
I expected to see the difference from the previous deployed version to the new version in the changelog.
In case of a previous release downgrade, the detection of the comparison version number seems wrong to me. See steps to reproduce...

### Steps to reproduce the problem
For example, we have three Releases: 1, 2 and 3
- Deploy Release 1
- Deploy Release 2
- Redeploy Release 1
- Deploy Release 3
The release number to compare should be 1 (because this is currently deployed).
But it compares 3 with 2.

### Suggestion
The function `getPastSuccessfulRelease` should look for the deployment date of a release, not for the release id. If this information is available :-)

**Comment by rfennell** [comment]
This extension is designed to use the same API calls as the Microsoft provided UI feature that allows you to compare two releases, this is a single call that takes a couple of release IDs as parameters. Hence I cannot implement the change requested i.e. via date.

I suppose the other option would be to use different logic to work our which two IDs to uses, but at present I use the last successful release to the given (or overrriden) stage

**Comment by MarcDrexler** [comment]
I am not sure if you understand me correctly. It is totally fine that this extension uses the same API calls as the provided UI from Microsoft. This should not change.
The only thing what is different from the Microsoft UI to your extension is that they must use a different logic to find out the last successful release ID (Because they always compare to the correct release ID, even if a downgrade happened before).

I saw that you are iterating over all past successfully deployed releases in the function `getPastSuccessfulRelease`. Beginning in line 88.
So I thought this might be something we are able to change? Or does the release object in the json response not provide a 'date deployed' property? Is that what you mean?
Sorry my english is not the best.

**Comment by rfennell** [comment]
Ah yes I misunderstood, another user of the extension @gregpakes has asked me the same question recently, the issu is that our current understanding is that the API does not differentiate between a deploy or a redeploy, it only shows the last successful deploy (or redeploy), as you found.

Your suggestion is an interesting option to use the dates, but we are trying to see if Microsoft says there is anything new in the API that could help. But we could look at date based logic.

Irrespective of what answer we get, just to let you know I personally will not be looking at making any code changes, I am just doing some support calls when I can as I am off work on long term sick leave.

However, I am happy to accept PRs if you wish to look into different logic, I would just ask it implemented so it is possible to either use the current or new logic.

**Comment by gregpakes** [comment]
@MarcDrexler @rfennell 

I am going to submit a pull request fixing this very soon.

**Comment by gregpakes** [comment]
Pull request submitted:

https://github.com/rfennell/vNextBuild/pull/157

**Comment by rfennell** [comment]
I have done a build that created a new private package 1.4.1 for PR157 that passes basic tests, I can make this available to both of you @gregpakes @MarcDrexler  too test if you wish. I don't have the capacity to do fuller testing due to medical appointments, I definitely will be off line next couple of weeks at least.

If you wish to test the private build let me know your VSTS instance names today. But as I don't want to block you, or anyone who needs a public build  (such as for on prem usage) so will do a public release over the weekend if I hear nothing

**Comment by rfennell** [comment]
Release 1.4.1 is now available in the public marketplace. This include the PR #157.

I am probably going to be unavailable for the next couple of week due to medical treatment, but @ChrisLGardner will keep any eye open for the any new issues relating to this issue .

**Comment by rfennell** [comment]
Closing as this fix has been public for a few months
