### ISSUE TITLE
GenerateReleaseNotes: How can I use the default Release variables in my template?

### ISSUE THREAD

**Issue by MarcDrexler** [rfennell/vNextBuild#154]
### VSTS Extension you are using
*GenerateReleaseNotes Extension (XPlat)*

### Where are you running it?
*TFS 2017 Update 2*

### Version of Extension/Task
*currently public version*

### Expected behavior and actual behavior
I would like to use variables like `$Release.EnvironmentName` or `$Release.Artifacts.{Artifact alias}.BuildNumber` in my release notes template. These variables won't get replaced by the release note generator, so I don't know if this is just not possible, or do I have to use them in another way?
I have seen something like `$stagename` in one of your examples, but this ends up with an `undefined` result.

**Comment by rfennell** [comment]
I have only really tested using VSTS API variables, so the immediate answer is what you want is not supported at present,

However, all the other release variables should be exposed as environment variables (as listed at the start of the release log), but you will need to access them suitable javascript calls inlined into the template, might work but I am not sure without more research

**Comment by rfennell** [comment]
Hope the answer I gave in august helped, I am closing this issue as I have heard no more. Please re-open it if you need more assistance

**Comment by scuba6388** [comment]
It would be awesome to have a syntax for using environment variables!  I'd love to hear if anyone got this to work.

**Comment by rfennell** [comment]
The default release variables are listed [here in the MS Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch) 

A variable in the form **release.DefinitionId** is exposed as an environment variable **RELEASE_DEFINITONID**

This task is written in Node as shown [here](https://stackoverflow.com/questions/54215041/can-variables-in-azure-pipelines-be-used-in-nodejs-code)

I have not added any specific code to allow the accessing of environment variables via the templates It might work, never tried.

Happy to accept PRs of new features
