### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by gregpakes** [rfennell/vNextBuild#156]
I have found a few more issues with the Xplat release notes task and I want to get them fixed.  Unfortunately, I am struggling to build the extensions from a clean clone.

I have followed the instructions in the Wiki, but I presume they are wrong.  

Would it be possible for you to update them?

**Comment by rfennell** [comment]
Lets get to the bottom of your issues via email as we are doing then sort the documentation when we have the process correct

**Comment by rfennell** [comment]
Notes from email added to the [wiki ](https://github.com/rfennell/vNextBuild/wiki/Build-Extensions)
