### ISSUE TITLE
Missing task for increasing a number in a variable i build

### ISSUE THREAD

**Issue by Proxio** [rfennell/vNextBuild#164]
I found that "update build variable" could be used for increasing a variable in a release. I am looking for a task where I can increase the value of a variable in build. I want to use that variable as a buildcounter which should be part of my version number for the build.

**Comment by ChrisLGardner** [comment]
There is a built in variable for just that $(Rev:.r), this will increase each time you run a build. There is also $(Build.BuildId) which should increment automatically but is shared across the whole of TFS/VSTS so won't be a linear progression if you've got multiple builds. 

As an example I use this format for some of my builds: 

`$(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)`

This gives me something like:

`MainProject_TestBuild_Dev_20170822.1` for the first build and then that last 1 will increment every time I run that build today.

There are more variables available [here](https://www.visualstudio.com/en-gb/docs/build/define/variables#predefined-variables) that could prove useful.

**Comment by Proxio** [comment]
Hi Chris, thank you for the quick answer. 

I am going from team city builds to VS Team System builds. I want to be able to track how many builds has been made since the start, so I want to have a build counter which I can set to whatever it was in Team City. When I increase major and minor, I dont whant the buildnumber to start over, which is the case with Rev:.r

**Comment by rfennell** [comment]
I will get the manifest altered so you can use the task in a build as well as a release

**Comment by rfennell** [comment]
Release fixed in 1.5.x

**Comment by Proxio** [comment]
Hi, I have made these settings for my build step
![image](https://user-images.githubusercontent.com/4199398/29659965-2b34276a-88c0-11e7-9c8b-5d84a7362dc9.png)

And I get the following build error. See the log below:

> 017-08-24T09:30:50.5139645Z ##[section]Starting: Update Build Variable
> 2017-08-24T09:30:50.5139645Z ==============================================================================
> 2017-08-24T09:30:50.5139645Z Task         : Set variable on a build defintion
> 2017-08-24T09:30:50.5139645Z Description  : Set variable on a build defintion
> 2017-08-24T09:30:50.5139645Z Version      : 1.5.6
> 2017-08-24T09:30:50.5139645Z Author       : Richard Fennell
> 2017-08-24T09:30:50.5139645Z Help         : Version: 1.5.6. [More Information](https://github.com/rfennell/vNextBuild/wiki/BuildTasks-Task/)
> 2017-08-24T09:30:50.5139645Z ==============================================================================
> 2017-08-24T09:30:50.5149650Z Preparing task execution handler.
> 2017-08-24T09:30:50.9799675Z Executing the powershell script: d:\a\_tasks\BuildVariableTask_115030de-9ced-4d2f-ad01-8c42d20d0327\1.5.6\BuildVariableTask.ps1
> 2017-08-24T09:30:55.9092277Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "UploadString" with "3" argument(s): "The remote server returned an error: (403) Forbidden." ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
> 2017-08-24T09:30:55.9092277Z    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
> 2017-08-24T09:30:55.9092277Z    at System.Net.WebClient.UploadString(Uri address, String method, String data)
> 2017-08-24T09:30:55.9092277Z    at CallSite.Target(Closure , CallSite , Object , Object , String , Object )
> 2017-08-24T09:30:55.9092277Z    --- End of inner exception stack trace ---
> 2017-08-24T09:30:55.9092277Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
> 2017-08-24T09:30:55.9092277Z    at CallSite.Target(Closure , CallSite , Object , Object , String , Object )
> 2017-08-24T09:30:55.9092277Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
> 2017-08-24T09:30:55.9092277Z    at System.Management.Automation.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
> 2017-08-24T09:30:55.9092277Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2017-08-24T09:30:55.9272257Z ##[error]PowerShell script completed with 1 errors.
> 2017-08-24T09:30:55.9272257Z ##[section]Finishing: Update Build Variable

**Comment by rfennell** [comment]
That is a rights issue on the build account, check the wiki https://github.com/rfennell/vNextBuild/wiki/BuildTasks-Task

**Comment by Proxio** [comment]
I just saw it. Sorry for not reading first! :)
