### ISSUE TITLE
.NET Core Versioning fails if the version field is not present and TargetFrameworks is used

### ISSUE THREAD

**Issue by Jaternius** [rfennell/vNextBuild#166]
### VSTS Extension you are using

VersionDotNetCoreAssembliesTask

### Where are you running it?

VSTS

### Version of Extension/Task
1.19.2

### Expected behavior and actual behavior

**Expected:** The version (e.g. AssemblyVersion) element is correctly added to the .csproj when it was not present before.
**Actual:** Although the output claims otherwise, the .csproj was not modified.

### Steps to reproduce the problem

These steps assume that the "Version field to update" setting is left empty.

1. Create a new .csproj in the new format.
2. Instead of setting the `<TargetFramework>` property, set `<TargetFrameworks>` (e.g. `<TargetFrameworks>net46;netstandard2.0</TargetFrameworks>`).
3. Make sure to not include an `<AssemblyVersion>` element in the .csproj.
4. Execute the task on the .csproj.
5. Inspect the .csproj.

This is most likely caused because [the regex used to insert the AssemblyVersion element](https://github.com/rfennell/vNextBuild/blob/master/Extensions/Versioning/VersionDotNetCoreAssembliesTask.src/ApplyVersionToAssemblies.ts#L97-L98) is looking for `</TargetFramework>`, which is not present due `<TargetFrameworks>` being used.

A workaround is to simply add the field with a dummy value (e.g. `<AssemblyVersion>1.0.0</AssemblyVersion>` to the .csproj. In that case, the normal replacement takes effect.

**Comment by ChrisLGardner** [comment]
I think we could do things a little differently with that to handle both situations. 

The first easy option that occurs to me is to use a regex to check for </TargetFrameworks> and if it exists to use that in the replacement instead of just </TargetFramework>. 

I'll see what I can do with this, might be a little while before I can put together a PR but I'll try to get it done this month.

**Comment by ChrisLGardner** [comment]
I've updated the task to now check for TargetFramework or TargetFrameworks and update correctly. I'll have a release out later today hopefully.
