### ISSUE TITLE
.NET Core Versioning fails. Product Version field not updated

### ISSUE THREAD

**Issue by AndrewJWaite** [rfennell/vNextBuild#167]
When packaging nupkg files, the version of the nupkg file is always 1.0.0.

Inspecting the assembly, the File version field has been updated but not the Product version field. Even though in the task:

*Advanced > The version field to update*

is empty, suggesting all fields should be updated.

Might be related to issue #166

### VSTS Extension you are using
VersionDotNetCoreAssembliesTask

### Where are you running it?
VSTS

### Version of Extension/Task
V1.19

### Expected behavior and actual behavior
**Expected**
File version, Product version fields updated and nupkg file name contains build number

**Actual**
File version updated, but Product version and nupkg filename is not

### Steps to reproduce the problem
1. Create csproj to publish a nupkg (with  <TargetFramework>net46</TargetFramework>)

2. Build steps
 a. Dotnet Restore
 b.  Version .NET Core Assemblies
 c. Dotnet Build
 d. Dotnet pack (csproj)

3. Check build output

**Comment by rfennell** [comment]
Yes that seems like a bug, I will try to have a look at it, but if it is not this week it won't be for a a couple of weeks at least due to being offline

**Comment by AndrewJWaite** [comment]
Thanks for the quick reply @rfennell

**Comment by ChrisLGardner** [comment]
I've updated the task to now change the product version as well. I'll have a release out later today hopefully.
