### ISSUE TITLE
BuildVariableTask loses data in build definition

### ISSUE THREAD

**Issue by rayjb6** [rfennell/vNextBuild#168]
### VSTS Extension you are using
Using the "Set variable on a build definition" task in a release to autoincrement a variable on the primary build artifact.

### Where are you running it?
Running in VSTS

### Version of Extension/Task
v1.5.6 of task.

### Expected behavior and actual behavior
Variable is correctly incremented, but other data in the build definition is dropped, including all variable groups and all conditions on conditional tasks.

### Steps to reproduce the problem
Add variable groups to a build and/or custom conditions to a task in the build. Run the release for that build with the "set variable" task. After the release completes, note in the history of the build definition that the project build service agent user created a new version of the build definition that does not include the variable groups and task conditions.

**Comment by rayjb6** [comment]
On further investigation, there are two main differences I see in the JSON data for the build definition: task conditions and variable groups (there may be others, but those are the ones I am using).
The script for v1.5.6 of the task specifies version 2.0 of the REST API. If I make the REST API call with no version specified the task conditions are included but variable groups are not, so maybe this issue is due partly to the version of the API that the task is specifying, and partly to the REST API running behind the functionality that is currently available in VSTS (not sure if that is the case or not). That seems to create some inherent risk in using this task, unless there is some other way of doing the update that doesn't run the risk of dropping recent build configuration.

**Comment by rfennell** [comment]
The task has never been tested with variable groups, so your analysis seems very reasonable. Lets hope a simple API version change will sort it.

Only issue is I am not sure when I will be able to get around to looking at this as off line for a few weeks after tomorrow

**Comment by rayjb6** [comment]
Just to clarify, this task was not being used to try to modify a variable in a variable group, it was only being used to modify a variable contained in a build that happened to also reference variable groups.
On further research, it looks like the json visible when comparing revision history for the build in the VSTS web interface matches the json returned from v4.0-preview of the API.

For now, I disabled this task where we are using it. We'll handle the variable updates manually when needed. Maybe exposing an API version parameter under "Advanced" would help.

As a nice to have, setting the comment property when saving the changes would be helpful. Currently it just repeats the comment from the previous revision of the build definition under the Project Collection Build Service user.

**Comment by ChrisLGardner** [comment]
This will be fixed in 1.6.x later today.
