### ISSUE TITLE
Filter builds from a particular source branch

### ISSUE THREAD

**Issue by gigeld** [rfennell/vNextBuild#169]
### VSTS Extension you are using
GenerateReleaseNotes

### Where are you running it?
VSTS

### Version of Extension/Task
latest

### Expected behavior and actual behavior
When generating release notes between deployments to specific environments, is it possible to select builds from a particular source branch? (our release pipeline has deployments from 'develop' and 'master' branch but we only need release notes generated for the 'master' branch)

**Comment by ChrisLGardner** [comment]
I haven't tested this but I think you could handle this using the build filtering on the environment within a release pipeline. Tarun Arora has a great blog post about that [here](http://www.visualstudiogeeks.com/DevOps/TeamServicesOneBuildDefinitionToRuleThemAll). I'll try to test this at some point to see if it will work for what you're asking but assuming you're following a similar process to this then I think it should work as we're pulling the work items linked to the build itself.

If you're doing things slightly differently then I'd need a bit more information on what your process looks like to investigate what is possible with the API and how we generate the required work items etc.

**Comment by gigeld** [comment]
We have a release pipeline that takes artifacts built from 'develop' and 'master' branches: the ones from develop are deployed to Dev and DevTest and the ones from master are deployed to Test, Stage and Prod.
The release notes are generated in 'Test' environment using as stage the last successful deployment on Prod. So, it covers all builds done during this time from, both branches, but we only need release notes from 'master' branch.

**Comment by ChrisLGardner** [comment]
You could make use of the Custom Conditions to restrict when the task is run. Some details [here](https://docs.microsoft.com/en-gb/vsts/build-release/concepts/process/conditions) suggest that you can do this pretty easily by checking which branch the build is from. 

If that doesn't work out of the box you can have a small PowerShell step which checks the environment variable `$(Build.SourceBranch)` for which branch it is and sets a flag using the Write-Host method of setting build variables. Something like this should do what you want:

```
if ($Env:BUILD_SOURCEBRANCH -eq 'master') {
Write-host "##vso[task.setvariable variable=IsMaster]$true"
}
else {
Write-host "##vso[task.setvariable variable=IsMaster]$false"
}
```

**Comment by gigeld** [comment]
That should be pretty straightforward but we have Custom Conditions in tasks used only in build definitions. In release definitions all tasks have only four control options:
 - Enabled
 - Continue on error
 - Always run
 - Timeout

**Comment by ChrisLGardner** [comment]
Are you using the new editor or the old one? Looking on some releases I have and I get the same options when using the old editor but swapping to the new one gives me the custom conditions on those same tasks.

**Comment by gigeld** [comment]
I haven't noticed this but it seems to be correct - with the new editor I can see the Custom Conditions for regular tasks.
Unfortunately we use the 'Generate release notes' task bundled in a Task Group where the new editor is not available yet. Probably we may have to use it as a separate task for now.
Thank you for your help!

**Comment by rfennell** [comment]
@gigeld I am doing a bit of house keeping on the issue list. Are you happy for me to close this issue? If I hear nothing for a week I will close it, but feel free to reopen if you need to
