### ISSUE TITLE
Extension does not work with Visual Studio 2015

### ISSUE THREAD

**Issue by JPGRodrigues** [rfennell/vNextBuild#17]
In my build server I only have Visual Studio 2015 installed and the extension is unable to set dacpac project versions.

The error is:2016-06-06T16:43:14.2928789Z ##[error]Unable to find type [Microsoft.SqlServer.Dac.DacSchemaModelStorageType]. Make sure that the assembly that contains this type is loaded.
2016-06-06T16:43:14.3085043Z ##[error]Unable to find type [Microsoft.SqlServer.Dac.DacSchemaModelStorageType]. Make sure that the assembly that contains this type is loaded.
2016-06-06T16:43:14.3085043Z ##[error]Unable to find type [Microsoft.SqlServer.Dac.DacSchemaModelStorageType]. Make sure that the assembly that contains this type is loaded.

**Comment by rfennell** [comment]
I think this is related to #18 
The version DACpac task does assume that Visual Studio is installed in the default location - this is with hindsight an un-reasonable assumption. 
I will refactor the code to provide an extra parameter to allow the root folder for the SQL tools to be specified.
I will release this ASAP

**Comment by rfennell** [comment]
Just published version 1.3.3 of the manifest versioning extension, this allow the toolpath to be set for the DACPAC tools, it is on the advanced section. If left blank the default SQL 2014 and 2012 locations are used.

**Comment by rfennell** [comment]
Did this fix your problems?
