### ISSUE TITLE
Missing script files from .NET Core Versioning Task... Again

### ISSUE THREAD

**Issue by rdefreitas** [rfennell/vNextBuild#173]
### VSTS Extension you are using
Version .NET Core Assemblies

### Where are you running it?
VSTS both Private and Hosted VS 2017 build agents

### Version of Extension/Task
1.19.3

### Expected behavior and actual behavior
**Expected**
.NET Core Assembly version updated.
**Actual**
Task fails with error message:
File not found: 'C:\agent\_work\_tasks\VersionDotNetCoreAssemblies_4578fa22-6039-4d83-90e0-3e12f68d6b26\1.19.3\ApplyVersionToAssemblies.js'

### Steps to reproduce the problem
Use the Version .NET Core Assemblies build task

**Comment by ChrisLGardner** [comment]
Looks like I broke something with that minor documentation change.

I'll have a look at this and get it sorted ASAP

**Comment by ChrisLGardner** [comment]
New update being rolled out now that should fix it. 

I've hopefully fixed the build process to prevent it happening in future too but I'll keep a close eye on it and be more thorough with my testing.

**Comment by rdefreitas** [comment]
Thanks, @ChrisLGardner. That did the trick.
