### ISSUE TITLE
.NET Core Versioning assumes same version number structure in process and csproj

### ISSUE THREAD

**Issue by esbenbach** [rfennell/vNextBuild#176]
### VSTS Extension you are using
VersionDotNetCoreAssembliesTask

### Where are you running it?
VSTS

### Version of Extension/Task
1.19

### Problem Description
The extension uses the same regular expression to find the existing assembly version in the .csproj as it uses to parse the version number from the "$(VersionNumber)" variable of the task.

### Steps to reproduce the problem
Use a $(VersionNumber) task variable that contains a different scheme for the one present in the <AssemblyVersion> field of the .csproj

### Solution suggestions
Replace all of the <AssemblyVersion>Whatever</AssemblyVersion> string with a new <AssemblyVersion>DETECTEDBUILDNUMBER</AssemblyVersion> string instead.

**Comment by ChrisLGardner** [comment]
So as an example are you finding something like:

csproj has 1.0.0.0
$(VersionNumber) has 1.0.0 

If so then I'll have to look at how we currently do things with the task but I think I have a few possible solutions I can try to fix this.

**Comment by esbenbach** [comment]
Ill submit a pull request, then you can consider my solution or discard it
as you please :-)

**Comment by ChrisLGardner** [comment]
Merged PR, will push out a new release later today.
