### ISSUE TITLE
Filename Pattern does not work for Version .NET Assemblies Task

### ISSUE THREAD

**Issue by patnolan** [rfennell/vNextBuild#177]
Hi I would like to use your Version .NET Assemblies Task, however, it does not seem to work for me.

I am working with a legacy codebase and therefore cannot change how versioning is managed.

In this situation, the AssemblyVersion attribute is located in the "VersionInfo.cs" which is located in the same directory as the solution. The VersionInfo.cs is included in each project of the solution via a linked file.

I have set the "FileName Pattern" property on the Task to "VersionInfo.cs", however, the AssemblyVersion attribute is not updated.

Could this be fixed sometime soon?

Thanks heaps!

**Comment by patnolan** [comment]
Hi...Just checking if this is something that can be resolved soon?

**Comment by ChrisLGardner** [comment]
Hi

I should be able to look at this in the next few days and hopefully I can come up with a fix that will solve this for you.

**Comment by patnolan** [comment]
Thanks heaps!

**Comment by ChrisLGardner** [comment]
I'm looking at this and I think I can see where the problem is, just to confirm it can I get a run down of the various properties you're passing to the task? And can you check the log file (possibly with System.Debug = True) to see if the task is picking up any files to change the version on?

If you're using something like $(Build.SourcesDirectory) as the root directory, is the solution in that directory with the VersionInfo.cs next to it?

**Comment by patnolan** [comment]
Hi Chris,

Below is the output for the task.
The file and attribute exists, however, nothing is being updated

**Task Output**
```
2017-10-20T06:45:30.6984929Z Executing the powershell script: C:\tfsbuild\tasks\VersionAssemblies\1.22.11\ApplyVersionToAssemblies.ps1
2017-10-20T06:45:30.7453653Z ##[debug]Source Directory: c:\build\1\s\e5 Anywhere\src
2017-10-20T06:45:30.7453653Z ##[debug]Filename Pattern: VersionInfo.cs
2017-10-20T06:45:30.7453653Z ##[debug]Version Number/Build Number: 3.7.7755.1
2017-10-20T06:45:30.7453653Z ##[debug]Version Filter to extract build number: \d+\.\d+\.\d+\.\d+
2017-10-20T06:45:30.7609917Z ##[debug]Field to update (all if empty): AssemblyVersion
2017-10-20T06:45:30.7609917Z ##[debug]Output: Version Number Parameter Name: OutputedVersion
2017-10-20T06:45:30.7609917Z ##[debug]Extracted Version: 3.7.7755.1
2017-10-20T06:45:31.7921682Z ##[warning]Found no files.
```

**Solution structure is** 
SampleProjectA
    Properties
        AssemblyInfo.cs
SampleProjectB
    Properties
        AssemblyInfo.cs
SampleProjectC
    Properties
        AssemblyInfo.cs
Sample.sln
VersionInfo.cs

Having had a quick look (and I could be wrong), the problem may be that in your powershell script you're only looking in the "Properties" or "My Project" folders. However, as we have a common VersionInfo.cs used across all projects which contains the versioning attributes our VersionInfo.cs is located at the same level as the solution file. If I was creating a new solution from scratch I would do this differently, however, this is legacy code and cannot be modified.

`$files = Get-ChildItem $Path -recurse -include "*Properties*","My Project"`

Thanks heaps for your quick response!

**Comment by ChrisLGardner** [comment]
Hi

That's exactly where the problem is, I know how to fix it reasonably easily but I'll have to do some testing to ensure it doesn't break anything else or have any odd side effects.

I'll try to get this sorted this weekend but it might end up being next week before I can get enough time to properly investigate.

**Comment by patnolan** [comment]
Thanks heaps. Greatly appreciated.

**Comment by ChrisLGardner** [comment]
New version will be out today that fixes this.
