### ISSUE TITLE
Build Parameters not populating

### ISSUE THREAD

**Issue by cmoye** [rfennell/vNextBuild#179]
### VSTS Extension you are using
TFS 2017
### Where are you running it?
 On-premise TFS 2017

### Version of Extension/Task
2.10.2
### Expected behavior and actual behavior
The build parameters are not populating because the build artifacts are in another project. When we hardcode the correct path to the project it works fine. I would be cool to have an option to select which project path to use.

### Steps to reproduce the problem

Set up a build in one project
Set up a release definition in release manager in another project
Add the generate release notes task to the release notes definition
Map the release definition to the artifact of the build in the other project
Run the release definition and the generate release notes task

**Comment by ChrisLGardner** [comment]
Hi

I'll try to look into this over the next week or so, I need to refresh myself on how the task works and we might be able to do something about this.

**Comment by cmoye** [comment]
thanks sounds good

**Comment by cmoye** [comment]
Any luck on this change?
