### ISSUE TITLE
Extension fails when Visual Studio is not installed in the default directory

### ISSUE THREAD

**Issue by JPGRodrigues** [rfennell/vNextBuild#18]
In my build server  visual studio is not installed in drive c: and the extension fails to run!

**Comment by rfennell** [comment]
I think this is related to #17
The version DACpac task does assume that Visual Studio is installed in the default location - this is with hindsight an un-reasonable assumption. 
I will refactor the code to provide an extra parameter to allow the root folder for the SQL tools to be specified.
I will release this ASAP

**Comment by rfennell** [comment]
Just published version 1.3.3 of the manifest versioning extension, this allow the toolpath to be set for the DACPAC tools, it is on the advanced section. If left blank the default SQL 2014 and 2012 locations are used.

**Comment by rfennell** [comment]
Did this fix your problems?
