### ISSUE TITLE
Enhancement request: Allow manipulation of variables before they are output into releasenotes

### ISSUE THREAD

**Issue by alexfoxetech** [rfennell/vNextBuild#180]
### VSTS Extension you are using
GenerateReleaseNotes

### Where are you running it?
TFS 2017 On-prem

### Version of Extension/Task
2.10.2

### Expected behavior and actual behavior
I would like to be able to use find/replace functionality on variables so I can format them exactly as I would like to for my release notes. Apologies if this is already possible I could not find documentation to support it.

### Steps to reproduce the problem
Example: $(Build.SourceBranchName) will currently resolve to 1.20 but I would like to manipulate it in the template so it is output as 1_20

**Comment by ChrisLGardner** [comment]
Hi

I'm not sure how possible this is, I'll have to dig into the task and look at how we might be able to handle this.

**Comment by alexfoxetech** [comment]
Thanks Chris! Anything you can do is appreciated, love the potential of this extension!

**Comment by alexfoxetech** [comment]
@ChrisLGardner is this task compatible with https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks

As this would solve this issue!

**Comment by ChrisLGardner** [comment]
It should be for most of the things you want to do with it. We're just using the environment variables that are populated by the build system, if you update them before running the Generate Release Notes task then it should use the updated version.
