### ISSUE TITLE
Task is Updating Referenced NuGet Package versions causing the build to fail

### ISSUE THREAD

**Issue by AndrewJWaite** [rfennell/vNextBuild#183]
### VSTS Extension you are using
VersionDotNetCoreAssembliesTask

### Where are you running it?
VSTS

### Version of Extension/Task
Currently public version

### Expected behavior and actual behavior
*Expected*
DotNet core related version numbers are updated in the csproj

*Actual*
DotNet core **and** referenced NuGet package versions are being updated in the csproj

### Steps to reproduce the problem
Create csproj with NuGet references

Build steps
a. Dotnet Restore
b. Version .NET Core Assemblies
c. Dotnet Build
d. Dotnet test

build fails

**Comment by AndrewJWaite** [comment]
Maybe related to the fix for #167

**Comment by ChrisLGardner** [comment]
It's definitely related to that fix. I'll see what I can do today to get this fixed, hopefully should just be an small update to the regex we're using.

**Comment by AndrewJWaite** [comment]
Thanks for the quick reply @ChrisLGardner. If you need any more information please let me know.

**Comment by ChrisLGardner** [comment]
As a quick check, are you specifying a version field to update under the Advanced options for the task?

I'm pretty sure that's what has broken it as it changed from AssemblyVersion to just Version. I'm leaning towards reverting that change and documenting that you need to specify the field to be called Version for it to update all the various version numbers that the resulting package uses.

The alternative is to modify the regex checking we're doing, I think this might be more sensible fix but will take a little more time to implement correctly.

**Comment by AndrewJWaite** [comment]
No, we have left that field blank.

Reverting works for me as we have disabled that task for now.

**Comment by ChrisLGardner** [comment]
Should have a new build out in about 10 - 15 minutes that fixes it.

**Comment by Rzpeg** [comment]
Experiencing the same issue now on Azure DevOps. The task is updating the referenced NuGet package versions. Maybe you should update the script to ignore the Version tag if inside the PackageReference tag ? At the moment, this gets updated:
  <PackageReference Include="Serilog.Exceptions">
      <Version>4.1.0</Version>
    </PackageReference>
