### ISSUE TITLE
$build.finishTime is null

### ISSUE THREAD

**Issue by wertzui** [rfennell/vNextBuild#19]
I'm using the basic template provided [here](https://github.com/rfennell/vNextBuild/blob/master/SampleTemplates/build-basic-template.md).
The "Generate Release Notes" Task ist the last step of my build definition.

I'm getting this error:
##[error]NULL kann nicht in den Typ "System.DateTime" konvertiert werden.
In english:
NULL cannot be converted to the type "System.DateTime".

I think, it comes from this line in the basic template:
**Build completed** $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.finishTime)   

Since the build is still running, $build.finishTime must be null.

You should exclude this line from the basic template, or better have some other sort of timestamp there.

**Comment by rfennell** [comment]
My mistake on the sample:

- When using the release notes task within a build the build is not finished so the finishedtime is not set, as you saw. 

- If you use the task within a release it is ok to use as the builds are completed before the release pipeline starts

I have there [edited the build sample](https://github.com/rfennell/vNextBuild/blob/master/SampleTemplates/build-basic-template.md) to read as below, it was my mistake mixing a build and release test example together sorry for the confusion
Build started : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)` 

Hope this sorts you our

**Comment by wertzui** [comment]
This is perfect, thanks for your quick response and fix :)

**Comment by pagadalacs** [comment]
Hi, I used the build sample, ths system.Date time error is solved. how about the 2016-06-20T11:17:01.8785767Z ##[error]Cannot find drive. A drive with the name ' D' does not exist. 

I still can see the drive name doesn't exst error. any ideas please ?
