### ISSUE TITLE
View PBI on Release Notes

### ISSUE THREAD

**Issue by miltoncamara** [rfennell/vNextBuild#192]
Is possible to get parent work items? People that receive this e-mail is not interesting to view tasks. I think they would like to see the use cases / pbi.

**Comment by ChrisLGardner** [comment]
I think it should be possible but I'd have to look into it.

**Comment by SWarnberg** [comment]
Same request as #92.

**Comment by rfennell** [comment]
I am closing this as it is a duplicate of #92 as stated above. Please follow #92 to track what we are doing over this change
