### ISSUE TITLE
New Task Idea - Task which turns username and password into PSCredential object for later use.

### ISSUE THREAD

**Issue by ChrisLGardner** [rfennell/vNextBuild#193]
Someone asked about passing in credentials into tasks and it doesn't look like the normal task variable types support that.  Having a task which takes a username, password and output variable name and turns them into a credential object for later use might be useful to have.

Need to investigate if it actually works when passing it around however.

**Comment by rfennell** [comment]
@ChrisLGardner will address this one in his own [GitHub Account](https://github.com/ChrisLGardner/)
