### ISSUE TITLE
Assembly version no longer being updated

### ISSUE THREAD

**Issue by kwarnke** [rfennell/vNextBuild#194]
### VSTS Extension you are using
*Version .NET Core Assemblies*

### Where are you running it?
*VSTS*

### Version of Extension/Task
*1.25.4*

### Expected behavior and actual behavior
Expecting the resulting assembly (dll) to have the correct version.  Actual behavior is it still has the default 1.0.0.0 version.

### Steps to reproduce the problem
Run my build

This worked in version 1.24.19.  And, to be honest, I'm not sure how my build configuration was automatically upgraded to 1.25.4.  I guess that's something that just happens automatically?

Thanks,
Kevin

**Comment by ChrisLGardner** [comment]
Updates to minor versions automatically get rolled out.

I'll have a look at this a bit later, I think I know what the problem could be so I'll just double check.

Can you look under Advanced in the task and check that a value is in the FileName Pattern? It should be AssemblyInfo.* or AssemblyInfo.cs or something similar.

**Comment by kwarnke** [comment]
Filename Pattern:
.csproj

This is ASP.NET Core with the csproj file structure.

Thanks for checking!

**Comment by ChrisLGardner** [comment]
That's what I get for skim reading, I assumed it was the normal .net versioning task.

The solution for that is to specify the field you want to modify to be AssemblyVersion. There was a change recently to default to Version instead as that populates a different field and filters through into nuget packages.

**Comment by kwarnke** [comment]
That did the trick.

Previously, my "The version field to update" was blank.  I updated it to "AssemblyVersion" and that corrected the problem.

Thanks!
