### ISSUE TITLE
Use API workaround to existing TFS bug that results in only 50 work items being displayed

### ISSUE THREAD

**Issue by alexfoxetech** [rfennell/vNextBuild#195]
### VSTS Extension you are using
Generate Release Notes

### Where are you running it?
TFS On-Prem 16.122.26918.3

### Version of Extension/Task
2.10.2

### Expected behavior and actual behavior
Current bug in TFS results in only 50 associated work items being returned for a build.
See https://developercommunity.visualstudio.com/content/problem/38322/tfs-2017-update1-associated-work-items-for-a-build.html for reference.

### Steps to reproduce the problem
Queue a build with more than 50 items, the build page (and the generate release notes task) will only return the first 50 work items.

We've found a workaround to this by passing $top=100 (etc.) in the API call to return 100 items instead of 50 but there is no way to customise this TFS build definition options, would it be possible to pass this parameter in the tasks API call? Could it possibly be a configurable option in the tasks options page?

Thank you.

**Comment by ChrisLGardner** [comment]
That should be possible. I'll try to look into that soon.

**Comment by alexfoxetech** [comment]
Thanks Chris

**Comment by rfennell** [comment]
@ChrisLGardner I have a bit more time, I will have a look at this and if it is OK make similar changes on the CrossPlatform version

**Comment by rfennell** [comment]
Released as 2.11.4 for this Powershell version of generate release notes

I previously mentioned looking at the cross platform version, this is a bit more complex as it uses currently undocumented API, so I am leaving it alone. Also where it is a valid setting in the xplat version it defaults to 250 or 1000. Which I guess is enough for most!
