### ISSUE TITLE
Release Notes: Name of release (override)

### ISSUE THREAD

**Issue by vercellone** [rfennell/vNextBuild#196]
### VSTS Extension you are using

Generate Release Notes Build Task

### Where are you running it?

VSTS

### Version of Extension/Task
2.10.2

### Enhancement request

Expose advanced parameter "Name of release (override)" along with "Name of stage (override)"; Both applicable only if "Generate for only this release" is unchecked.  This will allow release notes to be (re)generated both proactively and retroactively without actually triggering a deployment/potential outage.

**Comment by ChrisLGardner** [comment]
That's a pretty interesting idea. I'm not sure when I'll get a chance to look at this unfortunately.

**Comment by rfennell** [comment]
@vercellone  I have been looking into the practicality of this enhancement. 

Currently the tasks works out the  current release based on agent environment variables and its internal ID, not it's name e.g 1234 and not 'My_Release_7.3.1'. For this reason I am uncertain as to how the new parameter would work. So, I will try to go through my understanding of the request and what would need to happen

- Assume we have a release definition called 'My Product' with 3 stages
    - dev
    - qa
    - prod
-  We have had 5 releases of our product with the release names in the form 'My Product 1.1', 'My Product 1.2' etc.
-  For some reason we want to be able to regenerate the release notes for the stage 'qa' on the build 'My Product 1.4'. This means we would need to set the generate release notes task properties to
    - Stage override - qa
    - (the new option) Release override - 'My Product 1.4' (Behind the scenes would have to convert the name 'My Product 1.4' to its internal release number e.g. 3456.)

The problem I see is do you really want to have to put a fixed release name, importantly **NOT** a release **DEFINITION** name, in as a text based property entry field? You would have to edit it on virtually every run. This does not sound that practical, hardly a hands off automated process.

I see two other approaches that might be more practical
1. Add another stage to the process. This extra stage would contain the generate release notes task alone, but uses the override stage to point to another stage. This would allow this documentation stage to be redeployed without effecting anything other than the documentation generation. This could be repeated for any or all stages e.g.
     - dev
     - qa
     - qa release notes, just contains the release not task with the override stage set to qa
     - prod
     - prod release notes, just contains the release not task with the override stage set to prod
1. Could this requirement not better served by a simple command line script? The task code base is such that all the work is done in a PowerShell module so calling this from a dedicated PowerrShell script would be easy to do. If this is appropriate, maybe your requirement is better server by you forking this repo and you adding the extra parameters to the module and produce a custom wrapper script.

Any thought on this response?
Did I understand the requirement correctly?

**Comment by vercellone** [comment]
Yes, you understood correctly.  Both approaches you've suggested are viable.  Thanks for your consideration.

**Comment by rfennell** [comment]
Ok, I that case I will close this issue for now while you try the work around.
