### ISSUE TITLE
Build Retension Task does not mark the Release to be retained indefinitely

### ISSUE THREAD

**Issue by deadlydog** [rfennell/vNextBuild#203]
### VSTS Extension you are using
Build Retension Task

### Where are you running it?
On prem, TFS 2017 Update 2

### Version of Extension/Task
Latest version, v1.6.2

### Expected behavior and actual behavior
I would expect the task to retain both the Build and the Release, but it seems to only mark the build to be retained. I'm guessing this was just an oversight when the task was created, but it would make sense to have it do both.

### Steps to reproduce the problem
Use the task as expected.

**Comment by rfennell** [comment]
You make valid points here. I think the historic issue is that when I wrote the task it was a good while ago and Release Management was very young (the old model that has an separate server, prior to it all being linked to the same agent model as used for builds). At that time it has no public REST API. Hence I could not write the features (though I admit I never thought to do it either).

On looking at the API and Docs (https://docs.microsoft.com/en-us/vsts/build-release/concepts/policies/retention) for Releases setting retention is not a simple boolean flag, it  is based on days etc. and reflects how artifacts should be retained as well as releases. 

I know from past conversation with the release management team at Microsoft that they see their current retension rule based systems, which also controls which artifacts are kept, is the way forward.

Hence my simple tasks is currently deemed to simplistic given the way release management as evolved. Though we still find it useful.

I have marked this as an enhancement, but also won't fix as I agree the built in model is probably the way forward. If I were to add this functionality I would be tempted to add it as a new task anyway as it really would be very different and should be cross platform which this version is not.

Hope that helps provide some context

**Comment by deadlydog** [comment]
Thanks for the reply back @rfennell. I actually found [a different extension](https://marketplace.visualstudio.com/items?itemName=haribabubavanari.BuildReleaseSetRetention-Tasks) that marks both the build and release to be retained forever, so I'll use that. People may still find yours useful though when they only want the build to be retained. Thanks!

**Comment by rfennell** [comment]
Good news you got what you needed in another task. It is great their is such an extensive marketplace these days that allows this these days

It is always going to be the case when extensions have their root inside a company that our features are not correct for everyone's needs
