### ISSUE TITLE
@@WILOOP@@ and @@CILOOP@@ tags are present in output MD file

### ISSUE THREAD

**Issue by jwestes** [rfennell/vNextBuild#21]
When inspecting the output markdown file, I see that the build details are present, but the loop tags have not been replaced with Work Items and Commits.  Below is the log and a snippet from the output file.

--LOG--
2016-06-22T10:16:39.9643711Z Executing the powershell script: E:\Agent\tasks\GenerateReleaseNotes\1.3.22\GenerateReleaseNotes.ps1
2016-06-22T10:16:40.3550094Z ##[debug]collectionUrl = [https://XXX.visualstudio.com/]
2016-06-22T10:16:40.3550094Z ##[debug]teamproject = [XXX]
2016-06-22T10:16:40.3550094Z ##[debug]releaseid = []
2016-06-22T10:16:40.3550094Z ##[debug]buildid = [3435]
2016-06-22T10:16:40.3550094Z ##[debug]defname = [Nightly Build]
2016-06-22T10:16:40.3706385Z ##[debug]buildnumber = [20160622.1]
2016-06-22T10:16:40.3706385Z ##[debug]In Build mode
2016-06-22T10:16:40.3706385Z ##[debug]Getting build details for BuildID [3435]
2016-06-22T10:16:41.3237744Z ##[debug]Getting associated work items for build [3435]
2016-06-22T10:16:41.3237744Z ##[debug]Getting associated changesets/commits for build [3435]
2016-06-22T10:16:44.8238348Z ##[debug]Using template mode [InLine]
2016-06-22T10:16:44.8238348Z ##[debug]Using in-line template
2016-06-22T10:16:44.9175848Z ##[debug]Processing template
2016-06-22T10:16:45.7769872Z ##[debug]Writing output file [e:\builds\5\a\releasenotes.md].

--RELEASENOTES.MD--
<p><strong>Build Number</strong>  : 20160622.2<br>
<strong>Build started</strong> : 22/06/16 06:23:33<br>
<strong>Source Branch</strong> refs/heads/master  </p>

<h3><a id="user-content-associated-work-items" class="anchor" href="#associated-work-items" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewBox="0 0 16 16" width="16"><path d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg></a>Associated work items</h3>

<p>@@WILOOP@@  </p>

<ul>
<li><strong> </strong> [Assigned by: ] <br>
@@WILOOP@@<br></li>
</ul>

<h3><a id="user-content-associated-change-setscommits" class="anchor" href="#associated-change-setscommits" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" height="16" version="1.1" viewBox="0 0 16 16" width="16"><path d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg></a>Associated change sets/commits</h3>

<p>@@CSLOOP@@  </p>

<ul>
<li><strong>ID </strong> <br>
@@CSLOOP@@<br></li>
</ul>
</article>
  </div>

</div>

**Comment by rfennell** [comment]
In the log you should expect to see

```
2016-05-20T06:40:50.6975546Z ##[debug]Using in-line template
2016-05-20T06:40:50.7055540Z ##[debug]Processing template
2016-05-20T06:40:50.7285529Z ##[debug]   Starting block WI
2016-05-20T06:40:50.7345521Z ##[debug]      0 items
2016-05-20T06:40:50.8405449Z ##[debug]   Ending block WI
2016-05-20T06:40:50.8435441Z ##[debug]   Starting block CS
2016-05-20T06:40:50.8455430Z ##[debug]      0 items
2016-05-20T06:40:50.8465441Z ##[debug]   Ending block CS
```

My guess is there is stray white space in the template file. can you try reentering from sample in this sites wiki

**Comment by jwestes** [comment]
That is where this template came from, (Build-Basic).  I have tried it as both File and In-line with the same results.  The only modifications made to the file/template is to remove the white-space at the beginning and end of the file.

**Comment by rfennell** [comment]
Just retested with 1.3.22 using the same template from the wiki and all seems OK to me, it finds CS and WI (or lists the fact it found none).

When recopying the template in I had a thought, you did flip to 'raw' format before copying the file contents in the GitHub code browser? I think this could cause problems as the web UI will intercept some of the markdown. 

After that I am stumped

**Comment by jwestes** [comment]
I downloaded the file and copied the text from Notepad++.  I'm going to try the build-dump template to see if it does any better.  I'll send an update when I know more.

**Comment by jwestes** [comment]
Could it have anything to do with the fact that I am doing this with an on premise build agent?

**Comment by jwestes** [comment]
I got it...  When you download the file there is a whole bunch of extra garbage that is included.  After viewing the file in the browser and switching to RAW view to copy it that way it works.  My template that did not work looked something like...  It is over 700 lines long, so I only included the top 50 lines or so.


<!DOCTYPE html>
<html lang="en" class=" is-copy-enabled is-u2f-enabled">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
    <meta charset='utf-8'>

    <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/frameworks-ef5cd9a5c1c1dd866688ad9da07b60d918f5a33a58f0de74d6fca585158075cb.css" integrity="sha256-71zZpcHB3YZmiK2doHtg2Rj1ozpY8N501vylhRWAdcs=" media="all" rel="stylesheet" />
    <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github-684460c0372793e6ec1dfda50bc3b70af24d9e6ecbefc25a6105c505bec219ea.css" integrity="sha256-aERgwDcnk+bsHf2lC8O3CvJNnm7L78JaYQXFBb7CGeo=" media="all" rel="stylesheet" />
    
    
    
    

    <link as="script" href="https://assets-cdn.github.com/assets/frameworks-f9a40617e5ea71342dc57103554b07a3c1edc88712b04de1a040aed44891a11d.js" rel="preload" />
    
    <link as="script" href="https://assets-cdn.github.com/assets/github-b50a231aa2d07a069508f5357c1fe8e3693335b1bc679fa0019ff69ec45ec7ef.js" rel="preload" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta name="viewport" content="width=device-width">
    
    
    <title>vNextBuild/build-dump-template.md at master · rfennell/vNextBuild</title>
    <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub">
    <link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
    <meta property="fb:app_id" content="1401488693436528">

      <meta content="https://avatars0.githubusercontent.com/u/324718?v=3&amp;s=400" name="twitter:image:src" /><meta content="@github" name="twitter:site" /><meta content="summary" name="twitter:card" /><meta content="rfennell/vNextBuild" name="twitter:title" /><meta content="vNextBuild - My TFS vNext build task and scripts" name="twitter:description" />
      <meta content="https://avatars0.githubusercontent.com/u/324718?v=3&amp;s=400" property="og:image" /><meta content="GitHub" property="og:site_name" /><meta content="object" property="og:type" /><meta content="rfennell/vNextBuild" property="og:title" /><meta content="https://github.com/rfennell/vNextBuild" property="og:url" /><meta content="vNextBuild - My TFS vNext build task and scripts" property="og:description" />
      <meta name="browser-stats-url" content="https://api.github.com/_private/browser/stats">
    <meta name="browser-errors-url" content="https://api.github.com/_private/browser/errors">
    <link rel="assets" href="https://assets-cdn.github.com/">
    <link rel="web-socket" href="wss://live.github.com/_sockets/ODczODgyMjoyNjdiYzQ1ZWU3NDdkYmEwZDA2NWExYTI1MDhiMTMwMzo1MjM4ZmVlNmFiMmY0ZTZkMTA1YTdjNjc4NGM5YWNkZmNmNTdlOTQyYTg2ZjVlNjUxNzZkNzczNzE2NGExZjNi--d33c441d38a5f8daf98df402c02c3c041cc8bd8e">
    <meta name="pjax-timeout" content="1000">
    <link rel="sudo-modal" href="/sessions/sudo_modal">
