### ISSUE TITLE
Crossplatform GenerateReleaseNotes not available for builds in VSTS

### ISSUE THREAD

**Issue by nlotra** [rfennell/vNextBuild#223]
Currently, I can see the Powershell version available to builds in VSTS but not the crossplatform version. I need it to work on a Linux build agent. Please make this available for builds too.

**Comment by rfennell** [comment]
Sorry the cross platform version uses the Release Management VSTS API. This means it works differently, so is not applicable to builds, see the [wiki for more details](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task)

To get what you require, I would have to port the PowerShell version to NodeJS. This would be a lot of work and not something I have any plans to do. Hence, closing this issue
