### ISSUE TITLE
List All Work Items and Commits/Changesets Associated with an Entire Development Branch in the Release Notes

### ISSUE THREAD

**Issue by emre-aki** [rfennell/vNextBuild#224]
### VSTS Extension you are using
Generate Release Notes Build Task

### Where are you running it?
TFS Version 16.122.27102.1

-----------------------------------------

I have used the extension to get the lists of work items and commits/changesets for a particular build. However, I am working in a CI environment where pull requests and subsequent merge commits are done frequently by various team members, which, in return triggers its associated CI build. In that build definition, we have included the 'Generate Release Notes Build Task'. 

In such a use case, our output file (named ReleaseNotes.md), gets overwritten everytime when such a merge commit is done and a subsequent CI build is triggered. Thus, we lose all of the earlier commits. What I want is a collective release note document including all the builds (and their associated workitems & changesets) triggered from a specific branch. Is such a thing even possible?Any sort of suggestion will be highly appreciated. Thanks in advance.

The following is the current output of my 'Generate Release Notes' build task:
-----------------------------------------

#Release notes for build DexmoMiddleware-Build  
**Build Number**  : 20171214.4    
**Build started** : 14/12/17 14:24:09     
**Source Branch** : refs/heads/0.2.0  
### Associated work items  
* **Product Backlog Item 154** [Assigned by: Onur Leblebici <UNIVERA\onur.leblebici>] complete missing dexmo core tests  
### Associated change sets/commits  
* **ID d8e2f155ceaae8f6b2169cc02f6ad82761f0c36c** log level tests added    
* **ID 8d8ed64d5948734d00afef5196689538798567bc** test code coverage improvements    
* **ID 958c30199cbe0326fde3816fdc6ff86c3d17c248** generic type class constraint added    
* **ID 6d8544d9c013e22a769b8bd79b9edbaa7480dce2** dexmo core test coverage improvements    
* **ID c3462ee78955e74cbf881a187fb9cc6c02fd3e47** Merged PR 22: test coverage ratio improvements

test coverage ratio improvements

Related work items: #154

**Comment by ahmeturganci** [comment]
I have same problem.

**Comment by rfennell** [comment]
A couple of quick fixes sprint to mind without a code change

- The **releasenores.md** file is configurable. You could make the release notes output file name something line **releasenote-($buildbuildnumber).md**
- The contents of the release notes file are also provided as a build output variable. You could use this as an input into a bit of inline PowerShell that appended the contents into a file.

Would either of these work?

**Comment by emre-aki** [comment]
Those _could_ both be somewhat a workaround, though what I want in the end of the day would a collective **ReleaseNotes.md** file which includes _all_ the builds triggered from their respective branch.

More specifically, say, I have a repository named _MyRepo_, and in that I have a _master_ branch, into which I regulary commit and push my source code. In our CI environment, every commit to _master_ triggers a build, and in that build definition, we include the task 'Generate Release Notes'. I want this task to list exacly each and every build that is triggered, as well as the workitems&changesets associated with it. However, as in the original post where I have attached the output of my build task, the Powershell script fetches only that particular build's associated workitems, and commit/changesets.

**Comment by emre-aki** [comment]
Exactly!

**Comment by rfennell** [comment]
That's do'able. I will try to get it done ASAP, probably be into the New Year

**Comment by emre-aki** [comment]
Actually, you probably do not have to rush it. I have investigated into the powershell source files .ps1 and .psm1 and found that you had used TFS API to perform REST calls to retrieve data related to work items based on build IDs. Would it be possible to modify this REST call similarly to get work items not based on their build IDs, but based on their branch/iteration path? That way I could list the work items associated with a given branch/iteration path in their entirety. That, indeed would be COMPLETE solution to my case, rather than a workaround.

**Comment by emre-aki** [comment]
> Actually, you probably do not have to rush it. I have investigated into the powershell source files .ps1 and .psm1 and found that you had used TFS API to perform REST calls to retrieve data related to work items based on build IDs. ***Would it be possible to modify this REST call similarly to get work items not based on their build IDs, but based on their branches/iteration paths?*** That way I could list the work items associated with a given branch/iteration path in their entirety. That, indeed would be a COMPLETE solution to my case, rather than a workaround.

Is there any update on this?

**Comment by rfennell** [comment]
I see no reason why that could not work and it might actual provide a solution. However, it is a good deal of work. Not sure when I will have enough time to undertake the work.

Also how do you see the branches/iteration path being passed in? 
- as parameters
- autodetched from the builds

**Comment by emre-aki** [comment]
I suppose it would be better if was automatically fetched from the build, since this is an all-automated CI workflow we are talking about.

**Comment by emre-aki** [comment]
Hello again @rfennell,

As I've mentioned in earlier comments, I'm trying to consume TFS RESTful API using WIQL to get workitems based on their iteration paths. To that end, I need to get the source branch whether from the build definition, or as a reference from TFS build environment variable. 

To provide some context, I am doing an Invoke-RestMethod request (its method being 'POST') within the powershell script and passing the query as `application/json` to the request as follows:

    {
        "query": "Select [System.Id], [System.Title] 
		       From WorkItems 
		       Where ([System.WorkItemType] = 'Bug' 
		              OR [System.WorkItemType] = 'Product Backlog Item') 
		              AND [State] <> 'Done'
		              AND [System.IterationPath] = <source_branch>"
    }

In our build environment, our iteration paths and source branch names are the same. Like I said, I need to replace the _**<source_branch>**_ with an actual reference to the source branch that the build is triggered from. 

_**In short**_, I've found that you have gotten some of the build details in `GenerateReleaseNotes.ps1` using the environment variables:

    # Get the build and release details
    $collectionUrl = $env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI
    $teamproject = $env:SYSTEM_TEAMPROJECT
    $releaseid = $env:RELEASE_RELEASEID
    $releasedefid = $env:RELEASE_DEFINITIONID
    $buildid = $env:BUILD_BUILDID
    $builddefname = $env:BUILD_DEFINITIONNAME 
    $releasedefname = $env:RELEASE_DEFINITIONNAME
    $buildnumber = $env:BUILD_BUILDNUMBER
    $currentStageName = $env:RELEASE_ENVIRONMENTNAME

Is there such a way that I can get the source branch from which the build is triggered as an environment variable, say, something like ` $sourcebranch = $env:BUILD_SOURCEBRANCH`? Any help on this will save my day. Thanks in advance!

**Comment by emre-aki** [comment]
Will give it a try and get back to you, @ChrisLGardner! Thanks.

**Comment by rfennell** [comment]
A new version of this extension has been released 2.15.5. One of its new features is that it allows the outputed release notes file to be appended too, as discussed in this issue

**Comment by rfennell** [comment]
If you want to know the branch a build is associated with then it is already available within a template as show below.

`$($build.sourceBranch)`

**Comment by rfennell** [comment]
I have had a think about this I don't intend to add this originally requested feature. I think the workaround of the appended to file feature is enough for now.

Happy to look at a PR if anyone has another idea
