### ISSUE TITLE
How to avoid merge PRs in changesets list?

### ISSUE THREAD

**Issue by TakhirMamirov** [rfennell/vNextBuild#248]
How can I avoid displaying merge pull requests coming into "Associated change sets/commits"? For instance, I wouldn't want the first line come up to the list as for the reader it may not add any sense since it's mostly a technical stuff:
```

ID 909a7883a37cdd8cf73e9262eedf473bca8e3f55 Merged PR 147: Changed release notes from md to html as html now works fine. Changed release notes from md to html as html now works fine. Cherry-picked from commit `ad7d61af`.
ID 6e969850eb2a653dbd9de71f5496a6d7728460f4 Changed release notes from md to html as html now works fine.
```

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I think there is nothing more that can be done. 

If this issue remains a problem or questions please do not hesitate to re-open it
