### ISSUE TITLE
Support passing version number to Version VSIX task

### ISSUE THREAD

**Issue by pascalberger** [rfennell/vNextBuild#25]
The Version VSIX task currently expects a build number from which it parses the version. This might be useful in some cases, but in my pipe I determine the version through GitVersion and have the version number already available in a variable. 

Therefore it would be nice if the version, as it will be written to the VSIX manifest, can be passed to the task.

**Comment by rfennell** [comment]
Not sure of that is a different task for could be handled by allowing an override version  number passed in  from a build variable?

**Comment by pascalberger** [comment]
Not sure if I understand correctly. You suggest a different task which allows to pass in the version number instead of build number?

IMHO it should be not a problem to add a second input which for the version, additional to the current input of the build number. User could then use either or.

**Comment by pascalberger** [comment]
This was fixed with https://github.com/rfennell/vNextBuild/commit/1ce0150e3b599af0a161d2f94a2c7983fdae22ff
