### ISSUE TITLE
Generate Release Notes returning work items that have seemingly no links to selected release

### ISSUE THREAD

**Issue by alexfoxetech** [rfennell/vNextBuild#250]
### VSTS Extension you are using
Generate Release Notes Build Task

### Where are you running it?
TFS on-prem Version 16.122.27102.1

### Version of Extension/Task
2.15.4

### Expected behaviour and actual behaviour
Using the task in a Release, Web view of TFS displays several work items as expected, however the template outputs literally hundreds of work items that in some cases are 2+ years old and not in anyway linked to the relevant release.

### Steps to reproduce the problem
Set up release task, following options are set:
Generate only for primary artifact - **unticked**
Generate for only this release - **ticked**
Show parent workitems - **unticked**

First build thrown out by the template returned around 500 items, TFS reports 91 linked to the release...

**Comment by rfennell** [comment]
The PowerShell based extension you are using uses its own logic to work out the linked items to a release; it scans across historic builds. You can see the builds it checks if you set the release variable of **system.debug = true** to get a detailed log. This logic differs from the logic used by the TFS Release UI that compares between releases. so you tend to see different results.

As this is not what most people want, to address this difference I wrote a second version of this extension, that has the added advantage of being cross platform, that uses the same Microsoft provided API calls as the TFS Release UI to get the linked item lists. 

Hopefully if you [swap to this other extension](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) you should get the results you expect

**Comment by alexfoxetech** [comment]
Thanks for the speedy reply Richard, I'll look into getting the extensions switched over now!
