### ISSUE TITLE
Question: will this extension be susceptible to the '50 work items limit' bug?

### ISSUE THREAD

**Issue by alexfoxetech** [rfennell/vNextBuild#252]
### VSTS Extension you are using
Generate Release Notes (crossplatform)

### Where are you running it?
TFS on-premise Version 16.122.27102.1

### Version of Extension/Task
1.6.2

### Expected behaviour and actual behaviour
My query is, is it likely that this extension will also be affected by the 50 items bug addressed for the PS version of this extension in [this issue](https://github.com/rfennell/vNextBuild/issues/195)?

I'm unable to obtain output from this task until a release is run (scheduled for tomorrow)

**Comment by rfennell** [comment]
I don't think it suffer that issue, but it is an undocumented apis I am using. I would test it

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I think the question is answered as bets I can. If this issue remains a problem please do not hesitate to re-open it
