### ISSUE TITLE
Generate Release Notes (Crossplatform) throws JSON error with artifact that does not contain work items

### ISSUE THREAD

**Issue by alexfoxetech** [rfennell/vNextBuild#256]
### VSTS Extension you are using
Generate Release Notes (Crossplatform)

### Where are you running it?
TFS on-prem version 16.122.27102.1

### Version of Extension/Task
1.6.2

### Expected behaviour and actual behaviour
We have an artifact that contains various scripts used in release deployment, it's a git repo in a project most users don't have access to. It will never contain work items so I'd like the task to be able to skip it if possible as it appears to be erroring the task and the markdown file fails to output:

2018-02-02T15:41:34.9168157Z Looking at artifact [ReleaseScripts]
2018-02-02T15:41:34.9168157Z Getting build associated with artifact. Build Id [3219246b6cedbb1ffafa1c20696b78aa5ebf901c]
2018-02-02T15:41:34.9168157Z Getting the details of build 3219246b6cedbb1ffafa1c20696b78aa5ebf901c
2018-02-02T15:41:34.9636924Z ##[error]Unhandled: Unexpected token < in JSON at position 2
2018-02-02T15:41:34.9792598Z ##[section]Finishing: Generate Release Notes V2

### Steps to reproduce the problem

Run the task with an artifact that does not contain work items.

**Comment by alexfoxetech** [comment]
Clarification, I also don't have access to these scripts so I don't know the contents of them.

**Comment by rfennell** [comment]
I have a test case in my CI/CD process that checks for no WI/Commits and I don't see this problem. So I suspect a local issue on your instance. This usually means a permission issue when an artifact is cross team/project and security locked down.

The API call that is failing is the REST call

`${vstsinstance}/${teamproject}/_apis/Build/Builds/${buildId}
`
I guess the next test is to try that call from a browser or postman on your system and see what is actually in the JSON being returned.

As I said, I think the most likely is that there is a permission issue, so  I expect this call when running as the build user PAT will get a 403 error or similar

**Comment by alexfoxetech** [comment]
Sorry for the delay getting back to you, have managed to grab the two relevant people and I've been assured that the TFS user that runs all builds/releases has admin permissions to the entirety of the TFS collection. I'll try my hand at a postman call tomorrow to see if I can get the exact data being returned.

**Comment by rfennell** [comment]
@alexfoxetech any news?

**Comment by alexfoxetech** [comment]
Hello, unfortunately I can't get any level of cooperation to test this issue, I've just been told the same thing as I posted above, that "the TFS user that does builds and releases has permissions to all of TFS".

As you've tested this and it works for you then this is likely a configuration issue on this end but it's very unlikely I'll be able to get it resolved or indeed feedback the ultimate problem to you.

**Comment by rfennell** [comment]
Ok, I will close the issue now, re-open it if you get more information
