### ISSUE TITLE
For a release definition, only latest build's WI's are listed

### ISSUE THREAD

**Issue by SWarnberg** [rfennell/vNextBuild#257]
### VSTS Extension you are using
GenerateReleaseNotes

### Where are you running it?
*VSTS

### Expected behaviour and actual behaviour
When using in a release definition, the task should list all work items for all builds since the last successful/triggered release. For instance, if Rel-1 is based on Build-1 and I create a Rel-2 that is based on Build-5, the work items from Build-2 to Build-5 should be included.  
However, only work items from Build-5 are included.

Staffan

**Comment by rfennell** [comment]
Which version of the task are you using, powershell or xpatform?

**Comment by SWarnberg** [comment]
It's the powershell version.  
Is it perhaps so that $lastSuccessfulRelease is wrong?

**Comment by rfennell** [comment]
Have you got a log file? That should show us what is going on.

You get more details if you run the release/build with the system.debug = true variable set

**Comment by SWarnberg** [comment]
Sure. Attaching it here.
[4_Generate Corrections document.log](https://github.com/rfennell/vNextBuild/files/1698367/4_Generate.Corrections.document.log)

**Comment by rfennell** [comment]
As you thought, it is only considering a single release

`Discovered [1] releases for processing after checking a total of [7] releases`

So I guess that this code is the issue

```
  foreach ($r in $allReleases | Where-Object { $_.id -le $releaseid })
        {
            if ($r.id -eq $releaseid )
            {
                # we always add the current release that trigger the task
                Write-Verbose "   Adding release [$r.id] to list"
                $releases += $r
            } else 
            {
                # add all the past releases where the this stage was not a success
                $stage = $r.environments | Where-Object { $_.name -eq $stageName -and $_.status -ne "succeeded" }
                if ($stage -ne $null)
                {
                    Write-Verbose "   Adding release [$r.id] to list"
                    $releases += $r
                } else {
                    #we have found a successful relase in this stage so quit
                    break
                }
            }       
        }
    }

```
I can't see how to get any further on this without improving the logging to let us know which route is being taken through that logic. 

I have just made the change and pushing it out, should taken a hour or so. It will be 2.16.x

**Comment by rfennell** [comment]
The log does confirm the exit route. The line

`$stage = $r.environments | Where-Object { $_.name -eq $stageName -and $_.status -ne "succeeded" }
`               
is the issue it seems, it should return a non-null value if there is a stage of the required name that is not successful, and then add the associated release to the list.

Am I misreading my own code?

I potential issue it that it will exit of there release was not attempted to a the active stage/environment of the current release.

**Comment by SWarnberg** [comment]
Hmm, my problem is not related to _unsuccessful_ releases. The problem is that $lastSuccessfulRelease is not set with the _last_ successful release. It is the new release.  
If you go further down, the $firstBuild variable need to be the first build after the last successful release.

**Comment by rfennell** [comment]
The _$lastSuccessfulRelease_ is not being set because the list of releases to consider is an array of size 1, hence the array[-1] the last item in the array is also the first, the current release.

I still think the issue lies in the fact the list of releases (and hence builds) since the last good release is wrong.

**Comment by SWarnberg** [comment]
Yes, the last good release need to be in the array. Hence the following scenario should be fulfilled:  

| Build | WI | Release | ReleaseNotes |  
| --- | --- | --- | --- |  
| Build-1 | WI1, WI2 | Rel-1 | WI1, WI2 |  
| Build-2 | WI3 |  |  |  
| Build-3 | WI4, WI5 |  |  |  
| Build-4 | WI6 | Rel-2 | WI3, WI4, WI5, WI6 |  

Both releases are successful.

**Comment by SWarnberg** [comment]
Maybe this can work?  


```
  $stage = $r.environments | Where-Object { $_.name -eq $stageName }
  if ($stage -ne $null)
  {
    Write-Verbose "   Adding release [$r.id] to list"
    $releases += $r
    if ($stage.status -eq "succeeded") {
      break
    }
    } else {
      #we have found a successful relase in this stage so quit
      break
    }
```

Then, maybe the last else block is not needed at all?

**Comment by rfennell** [comment]
What do you think of this

```
            if ($r.id -eq $releaseid )
            {
                # we always add the current release that trigger the task
                Write-Verbose "   Adding release [$r.id] to list as it is the current release"
                $releases += $r
            } else 
            {
                # add all the past releases where the this stage was not a success
                $stage = $r.environments | Where-Object { $_.name -eq $stageName }
                if ($stage -ne $null)
                {
                    if ($stage.status -eq "succeeded")
                    { 
                        # we have found a successful release in this stage so quit
                        # without adding this release to the set to process
                        Write-Verbose "   Finished adding releases as  [$r.id] successful release"
                        break
                    } else 
                    {
                        # Found an intermediate release we need to added
                        Write-Verbose "   Adding release [$r.id] to list as it is was an unsucessful release"
                        $releases += $r
                    }
                } else {
                    Write-Verbose "   Can't find any stages/enviroments that match the requested one $stageName"
                }
            }     

```

Also I think I a rename of the **$lastSuccessFulRelease** variable is needed to **$releaseAfterLastSuccessfulRelease** as this actual describes what it stores!

**Comment by SWarnberg** [comment]
Hmm, no I don't think that will work. Maybe you miss the point. If you don't add the previous **successful** release to the list, you won't be able to get the list of builds since the last release.  
Ref my table above: if you only add Rel-2 to the list, how can you get information about Build-2 and Build-3? Hence, you need Rel-1 in the list as well.

**Comment by rfennell** [comment]
Ah, I get you point, sorry for being slow.

However, why do you want the details of builds from the previous successful release in the current release's release notes? 

Would not those build details be in the previous set of release notes? - this had been my design assumption

**Comment by rfennell** [comment]
I can only apologise, your provided logic was fine, I was focusing too much on the release finding loop ignoring the logic I had in the build discovery.

I think you are right the final else is not needed.

I have implemented this in 2.17.x which is going into the release pipeline now, takes a while for the automated testing.

**Comment by SWarnberg** [comment]
Sounds great. Looking forward to test it.

**Comment by SWarnberg** [comment]
Hi,
I just tested it in production and it successfully included all builds. However, there is a side-effect that needs to be fixed.
Since a dev can check in many times associating the same wi, the wi may be associated with several builds. This caused the same wi to appear several times on the release notes.
Need to add an "exists" on the wi array.

Staffan

**Comment by rfennell** [comment]
Thought that was in there, I will investigate

**Comment by SWarnberg** [comment]
Now I think I understand why. You have the concept of @@BUILDLOOP@@ in a release workflow and add the WI's per build in a hashtable.
However, this is not how we like to have it. We need a flat list of unique WI's per release, because the customers or QA are only interested in "what has happened since the last release". They shouldn't bother about how many internal builds that have been triggered in between.
If there is a good reason to keep current behaviour, can I suggest a "flattened work items" option in the task to support customer release notes?

**Comment by SWarnberg** [comment]
Ref how TFS shows WI's since previous release:
![release2](https://user-images.githubusercontent.com/26246346/36041624-690316ee-0dc9-11e8-829d-c12deae58ee7.PNG)

**Comment by rfennell** [comment]
Remember my [XPlatform Generate Release Notes](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) uses the Microsoft API to get the same set of results as shown in the VSTS UI. You could consider switching to that extension

**Comment by SWarnberg** [comment]
Is the parent WI functionality implemented in that version?

**Comment by rfennell** [comment]
No it is not, and I won't add it to that task as it is designed to mirror the Microsoft functionality. 

IT is therefore a good job I am adding the flat list functionality to this version. :smile:

**Comment by SWarnberg** [comment]
Sounds good. Looking forward to test it.

**Comment by rfennell** [comment]
The revised version has been released as 2.18.27

**Comment by rfennell** [comment]
@SWarnberg is this working for you, can we close the issue?

**Comment by SWarnberg** [comment]
Yes. We have tested it, and it works well. We can close this issue now.
