### ISSUE TITLE
Require a full path filename pattern for package.json to avoid node_modules folder.

### ISSUE THREAD

**Issue by chrisfoster78** [rfennell/vNextBuild#261]
### VSTS Extension you are using
Manifest Versioning Build Tasks
VersionJSONFile

### Where are you running it?
VSTS - Local Agent

### Version of Extension/Task
1.32.2

### Expected behaviour and actual behaviour
I only want to version stamp a single package.json file in the root folder.  It is recursively looking through all subfolders including node_modules!

### Steps to reproduce the problem
Add an npm install task to install dependencies into node_modules. Execute a build twice on local agent without clearing files. 

I am currently working around the issue by clearing the folder for each build but would like to speed it up by leaving the node_modules behind from the previous build (default settings).  Is there already some way of specifying a full path pattern? I have tried .\package.json but nothing is found.

**Comment by rfennell** [comment]
Yes I can see that could be a problem. 

I think the best option is to add a boolean parameter to enable/disable recursion. I will look into getting it done

**Comment by chrisfoster78** [comment]
That would be great!  Thanks for the quick reply.

**Comment by rfennell** [comment]
This feature has been shipped as 1.33.1, let me know if it fixes your issue

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while and I think it is resolved. 

If this issue remains a problem please do not hesitate to re-open it
