### ISSUE TITLE
Add option to pass global parameters to the Pester task

### ISSUE THREAD

**Issue by rfennell** [rfennell/vNextBuild#265]
_Question raised via the [VSTS Marketplace Q&A for the Pester task](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-PesterRunner-Task#qna) by Chris Bergmeister_

Similar to schwaizi, this extensions is unfortunately not of any use if I cannot pass test system specific variables. I do this as follows:

```
$pesterConfiguration = @{Path='.'; Parameters=@{fancypants="$SecretValueFromVstsBecauseIDoNotWantToHardcodeInfrastructureRelatedStuffLikeMachineNamesOrCredentials"; port=$port}}
Invoke-Pester -Script $pesterConfiguration

```
This way any of my tests.ps1 files can receive those globally defined constants by defining a param block as follows:
```
Param
(
[Parameter(Mandatory=$true)]
[string] $fancypants,
[Parameter(Mandatory=$true)]
[int] $port
)
Describe "foo" {
It "bar {
# use parameter variables here
}
}
```

**Comment by rfennell** [comment]
I can't see an obvious reason this could not be added. The potential issue could be due to the way the tasks reloads the PowerShell session based in 32/64bit flags. That would need some investigation.

I have raised an issue for this enhancement on the project GitHub site

**Comment by bergmeister** [comment]
Thanks. At the moment, as a workaround, we added a boilerplate line at the start of each `*.tests.ps1` file that basically does `$configuration = &  (Join-Path $PSScriptRoot 'Get-GlobalConfiguration.ps1')`, which is a global helper returning a hashtable of settings that are read from a config file (that has default values, which get overridden by CI).

**Comment by rfennell** [comment]
This has been implemented and released in 6.2.20
What was the folder parameter is now the folder/script parameter it can accept either format.
@bergmeister  let me know if it works for your usecase

**Comment by bergmeister** [comment]
Wow, that was quick. Thanks. I'll take a look at it next week but I could already see the new help text and by looking at it it seems to be exactly what I was looking for.

**Comment by bergmeister** [comment]
@rfennell I just tried it and it works. The only thing that I noticed is that if I provide 2 parameters, then my `*.tests.ps1` files also need to accept those 2 parameters via the param block. My previous experience with Pester was that they were optional and I could just use the test parameters on a per need basis per test file but maybe this was a breaking change in a newer version of Pester.

**Comment by rfennell** [comment]
@bergmeister glad we got you unblocked. 

I don't think I can help on the need to declare parameters, so are you happy to close this issue?

**Comment by bergmeister** [comment]
Yes. Thanks, feel free to close.
