### ISSUE TITLE
Feature request: Consider adding ability to execute Pester task on remote machine.

### ISSUE THREAD

**Issue by bergmeister** [rfennell/vNextBuild#266]
### VSTS Extension you are using
Pester Extension

### Where are you running it?
VSTS

### Version of Extension/Task
Latest (6.1.36)

### Feature Request

Offer a checkbox to offer remote execution of Pester script using PowerShell WinRm based remoting along with username/password options for authentication. The remote machine is identified via FQDN or static IP address.
Then the minimum viable version of the extension assumes that Pester is already installed on the remote machine and basically handles:
- copying over the Pester script folder to the remote machine
- executing `Invoke-Pester` against this pester script folder on the remote machine
- copying the test results file back to the build agent

Let me know what you think. Since I might be going to implement something similar soon, so I might be able to provide the basic code snippets.

**Comment by rfennell** [comment]
I have had a chat about this with colleagues and we agreed this is certainly not a something to add to the current Pester task, it would at least be a separate task in the extension i.e. a Remote Pester task.

Also, given past experience with WinRM and making sure the correct code is on a target machine, there is a lot too much to go wrong communications wise.

I think the best option for this requirement would be to use the existing VSTS tasks to copy files to the remote machine, run remote PowerShell to invoke-pester, copy the results file back to the agent and finally publish results. These tasks could maybe be grouped into a task group. The main reason for this approach is to not re-invent the wheel for the complexities of remote PowerShell work.

**Comment by rfennell** [comment]
I am closing this issue as there is no plan to fix this, re-open if the scope changes

**Comment by bergmeister** [comment]
That's OK. With the recent unification of the build agents, the deprecation of the remote tests on machine and agent phases, we will soon see a change where agents will move more towards the SUT.
