### ISSUE TITLE
"Start a DevTest Labs VM" cannot be added as a VSTS Task

### ISSUE THREAD

**Issue by OmarMohammad** [rfennell/vNextBuild#274]
### VSTS Extension you are using
DevTestLab Extentions. Task "Start a DevTest Labs VM"

### Where are you running it?
VSTS

### Expected behaviour and actual behaviour
The extension is installed, but the task is missing. The task for stopping the VM is visible, but not for starting the VM.

### Steps to reproduce the problem
1- Add new or Edit existing Build Definition
2- Add Task to phase
3- search for "a DevTest Labs VM"
4- The result will show the "Stop a DevTest Labs VM" task but not  the "Start a DevTest Labs VM" task

![afbeelding](https://user-images.githubusercontent.com/17724871/36420035-fbca9b38-1633-11e8-9c3b-7f5530a2fcea.png)

**Comment by rfennell** [comment]
I can confirm I am seeing a similar issue, but I also have the Start task working, I will investigate

**Comment by rfennell** [comment]
The issue was the start task was only set to appear in releases, where as the stop task could be used in builds and releases. They can now be used in either with version 1.1.1
