### ISSUE TITLE
VersionJSONFileTask - Cannot specify outputFormat with 2.0.0-alfa.1

### ISSUE THREAD

**Issue by rfrcarvalho** [rfennell/vNextBuild#281]
### VSTS Extension you are using
VersionJSONFileTask

### Expected behaviour and actual behaviour
"Regex Filter to extract build number" is set to the default "\d+\.\d+\.\d+\.\d+"
"Version Format for JSON File" is set to "{1}.{2}.{3}-alfa.{4}"

With these values I was expecting to get a build number of something like 2.0.0-alfa.1 but instead i'm getting 2.0.0.1 which then makes the build process fail.
Looking at the code, it looks like you only care about the numeric values in the "outputFormat" variable. Would it be possible to consider the rest also, as it seems to be the standard for NPM packages.

![image](https://user-images.githubusercontent.com/4267071/37283224-16e3caf0-25ef-11e8-8385-00dde53701a2.png)

**Comment by rfennell** [comment]
Yes that seems a sensible enhancement to support SEMVER, I will look into it

**Comment by rfennell** [comment]
The logic has been revised to handle more complex delimiters as with SEMVER style
This has been released in 1.35.1.

Let me know if this fixes your problem

**Comment by rfrcarvalho** [comment]
This is working fine now. Thanks.
