### ISSUE TITLE
Pester Task could contain the current release of Pester - 4.3.1

### ISSUE THREAD

**Issue by JPRuskin** [rfennell/vNextBuild#286]
### VSTS Extension you are using
Pester

### Where are you running it?
VSTS

### Version of Extension/Task
Current

### Expected behaviour and actual behaviour
The included versions of Pester within this task are currently 3.4.3 and 4.0.8. The most recent version of Pester is 4.3.1, which contains [a few fixes](https://github.com/pester/Pester/blob/master/CHANGELOG.md).

We could update the included versions to be 3.4.3 and 4.3.1.

### Steps to reproduce the problem
Load extension, notice that the two versions available are 3.4.3 and 4.0.8.

**Comment by rfennell** [comment]
This has now been shipped as 7.0.1
