### ISSUE TITLE
Extensions/GenerateReleaseNotes - set file encoding to utf8

### ISSUE THREAD

**Issue by xtomik** [rfennell/vNextBuild#290]
### VSTS Extension you are using
Extensions/Generate Release Notes Build Task

### Where are you running it?
on-premise TFS 2018 update 2 RC1

### Version of Extension/Task
2.19.2

### Expected behaviour and actual behaviour
Actual: generated file with default encoding (ASCII)
Expected: UTF8

I would like to set explicitly the file encoding to UTF8.

**Comment by rfennell** [comment]
I will set this change made as it seems sensible

**Comment by rfennell** [comment]
Done and released as 2.20.1
