### ISSUE TITLE
"(Advanced) Text for empty sets" not used in release notes

### ISSUE THREAD

**Issue by jarhorn** [rfennell/vNextBuild#291]
### VSTS Extension you are using
Generate Release Notes

### Where are you running it?
VSTS Online

### Version of Extension/Task
current public version

### Expected behaviour and actual behaviour
Trying to get the default text set for empty Work Items collection.  I can see the Add Parameter with the correct key/value when I build in debug, but don't see it being used in the output. 

NOTE: I am using VSTS Hosted Build Agents / Octopus Deploy downstream to send mails

### Steps to reproduce the problem
1. Add **_Generate Release Notes_** build step to build definition.  I have attached a couple screenshots of my parameters.
![generate release notes configuration - general settings](https://user-images.githubusercontent.com/38043208/38255995-43b9dc7a-372b-11e8-8934-e42a16d31a3b.PNG)
![generate release notes configuration - advanced settings](https://user-images.githubusercontent.com/38043208/38255994-43a8546e-372b-11e8-83d7-d6e2424d37b0.PNG)
![generate release notes configuration - remaining](https://user-images.githubusercontent.com/38043208/38255996-43cbe046-372b-11e8-936c-ee0314f8b72e.PNG)
2. Queue a build with debug set to true
[Generate Release Notes Debug.log](https://github.com/rfennell/vNextBuild/files/1871989/Generate.Release.Notes.Debug.log)
3. Email sent downstream doesn't have the **Text for empty sets**

**Comment by rfennell** [comment]
Sorry I don't fully understand the issue, do you mean that the the email is empty if there are no WI associated with build?

Do you have a sample of the email (assuming it is not empty)

**Comment by jarhorn** [comment]
I added a Publish Build Artifacts step and here is the releasenotes.md it created (had to add the .txt extension to share)
[releasenotes.md.txt](https://github.com/rfennell/vNextBuild/files/1872267/releasenotes.md.txt)

**Comment by rfennell** [comment]
I get the issue now, I would expect the 'empty set' text to appear both the file and the output variable (email).

Sounds like a bug got introduced at some point, I will look into it

**Comment by rfennell** [comment]
The parameter was no being passed into a function correctly, this should now be fixed in 1.21.3

**Comment by jarhorn** [comment]
@rfennell -

I am getting duplicates of the $emptySetText now...  

Not a Powershell guy, so please forgive me suggesting when I am not an expert, but I *think* it maybe that because I don't have Change Sets and I don't have any Work Items, I hit the logic on line 535 and line 540? 

I didn't want to create another issue, hoping we can still use this one?  Thanks for your quick response!

**Comment by rfennell** [comment]
Lets reopen the issue as it is certainly not right, if you have not CS or WI then I would expect something like

```
#Release notes for build Validate-ReleaseNotesTask 
*Build Number* : 20180403.5 
*Build started* : 03/04/18 20:42:36 
*Source Branch* refs/heads/master

###Associated work items 
None 

###Associated change sets/commits 
None

```
Are you missing the second 'associated' title in you template?
