### ISSUE TITLE
Versioning: Avoiding that VersionDotNetCoreAssemblies updates .NET projects

### ISSUE THREAD

**Issue by EricSch** [rfennell/vNextBuild#295]
### VSTS Extension you are using
Versioning

### Where are you running it?
on-premise TFS 2018

### Version of Extension/Task
1.36

### Expected behaviour and actual behaviour
VersionDotNetCoreAssemblies updates .NET Core csproj files.
Actually all the .csproj are updated, even when they are normal .NET projects.

I know I could define the actual folder for the .NET Core project, but we have many VS solutions with mixed .NET versions and different Folder names. So it would be nice to check the .csproj Format first, for example .NET Core Projects starts with `<Project Sdk="Microsoft.NET.Sdk.Web">`
Thanks
### Steps to reproduce the problem
A VS Solutions with a .NET Core and .NET project

**Comment by rfennell** [comment]
An interesting suggestion, but the design assumption had been that the user would define a suitable path as you suggested in the issue.

**Comment by rfennell** [comment]
A quick check shows that `<Project Sdk="Microsoft.NET.Sdk*` would be a better check as the `web` is not used of class libraries (and I guess command line apps)

**Comment by EricSch** [comment]
Yes, I think so too. 
This enhancement would help me to avoid to edit each versioning-task in every build defintions and I could still use `$(Build.SourcesDirectory)` :smirk:.

**Comment by AndrewJWaite** [comment]
@rfennell 
I can confirm that fix worked for me.

```
2018-04-04T15:48:37.8013266Z Skipping file Nhh.Identity.AcceptanceTests.csproj as is not a .NETCore Project
2018-04-04T15:48:37.8073472Z Adding file Nhh.Identity.Domain.csproj as is a .NETCore Project
2018-04-04T15:48:37.8101831Z Adding file Nhh.Identity.Infrastructure.csproj as is a .NETCore Project
2018-04-04T15:48:37.8147388Z Adding file Nhh.Identity.Tests.csproj as is a .NETCore Project
2018-04-04T15:48:37.8186234Z Adding file Nhh.Identity.Web.csproj as is a .NETCore Project
2018-04-04T15:48:37.8201526Z Adding file Nhh.Identity.WebHost.csproj as is a .NETCore Project
```

**Comment by EricSch** [comment]
Thank you for the fast fix.
Probably worth to mention, that the task works with the new project file format, not with older .xproj files.

**Comment by rfennell** [comment]
Great news glad you are unblocked
