### ISSUE TITLE
Net Core project files not updating

### ISSUE THREAD

**Issue by pkillick** [rfennell/vNextBuild#298]
### VSTS Extension you are using
Version .NET Core Assemblies

### Where are you running it?
VSTS

### Version of Extension/Task
1.37.1

### Expected behaviour and actual behaviour
Logs read as if update has worked but .csproj files are not changed and output assembly does not have the expected version number under 1.37.1. This was woking under 1.35.1 a week or two ago. My code or build definition hasn't changed.

2018-04-05T14:02:45.0641976Z Source Directory:  D:\a\1\s
2018-04-05T14:02:45.0642497Z Filename Pattern: .csproj
2018-04-05T14:02:45.0642785Z Version Number/Build Number: 1.3.3.243
2018-04-05T14:02:45.0643201Z Version Filter to extract build number: \d+\.\d+\.\d+\.\d+
2018-04-05T14:02:45.0643499Z Field to update (all if empty): null
2018-04-05T14:02:45.0643802Z Output: Version Number Parameter Name: OutputedVersion
2018-04-05T14:02:45.0645343Z Extracted Version: 1.3.3.243
2018-04-05T14:02:45.0721311Z Adding file myproj.csproj as is a .NETCore Project
2018-04-05T14:02:45.0759541Z Will apply 1.3.3.243 to 4 files.
2018-04-05T14:02:45.0764660Z Updating all version fields with 1.3.3.243
2018-04-05T14:02:45.0766598Z Processing Field Version
2018-04-05T14:02:45.0767301Z Processing Field VersionPrefix
2018-04-05T14:02:45.0767958Z Processing Field AssemblyVersion
2018-04-05T14:02:45.0771479Z D:\a\1\s\myproj\myproj.csproj - version applied

**Comment by pkillick** [comment]
Seems to break because there is no version element already present in the .csproj file. Adding an empty one fixes the problem. Makes no difference whether a specific field is specified in "The version field to update" or it is left blank. The previous version would add version elements if not present.

**Comment by deadlydog** [comment]
I'm having this same problem. It would be great if it would add the required version field to the .csproj file if it doesn't already exist.

**Comment by rfennell** [comment]
Can I draw your attention to my response for #288. 

> The root issue here is that the field parameter documentation (tooltip) said leaving the parameter blank did one thing i.e. updating all the 'version' fields. However, in reality what it did was add a 1.2.3 field. This problem was down to an error in my code and associated poor testing.
> 
> This has caused confusion, as seen in these bug reports, so I needed to fix it.
> 
> All my options ended up being breaking changes of a sort; in the end I decided that treating the parameters options/documentation as being the correct specification was the best option, so made appropriate changes to the logic and added suitable unit tests to test all cases.
> 

I think the only other thing I can I do here is to add another field (boolean) of 'Add Version field if missing', but this would still be a breaking change, requiring build process editing. 

I would rather suggest that as others in #288 suggest

- Add an empty <VERSION></VERSION> to the csproj
- Add the VERSION tag to the tasks field property

**Comment by rfennell** [comment]
I think this issue is sorted, though with a breaking change issue as detailed above. Hence I am closing the issue.

Re-open or log anew issue if it is still an issue

**Comment by deadlydog** [comment]
Hey @rfennell I think it would make sense to add another boolean checkbox of `Add Version field if missing` to make it clear what the extension is doing, but I would also recommend that it be **enabled by default**.

I know there's also the workaround you mentioned of:
> Add an empty version element to the .csproj, and then add the VERSION tag to the task's field property.

The problem I have with both the workaround and adding the new boolean field (and _not_ having it enabled by default) is that your task won't do what people expect it to do. If I create a brand new vanilla .Net Core application, the version element is not added to the .csproj by default. So if I then used your extension and simply added it to my build process without making any changes to it, it wouldn't do anything. This would be confusing to users, and I think would result in more bug/issue reports. However, if you do add the new `Add Version field if missing` checkbox **AND** have it enabled by default, then your task would work as people would expect when used on a vanilla .Net Core application.

I'm not sure if you want to create a new `enhancement` issue for that new field request, or just reopen this issue to deal with it?

**Comment by rfennell** [comment]
I agree this is a good enhancement and have add a new issue #302 to track it
