### ISSUE TITLE
"Generate Release Notes V2.21.3" configuration bug

### ISSUE THREAD

**Issue by Bubleguy** [rfennell/vNextBuild#299]
### VSTS Extension you are using
Generate Release Notes V2.21.3

### Where are you running it?
Microsoft Visual Studio Team Foundation Server (on premise)
Version 15.117.26714.0

### Version of Extension/Task
Its is an older version on premise. We cannot upgrade at the moment for licence cost reason so if the problem is solved in future version it's ok, it's not a big issue.

### Expected behaviour and actual behaviour
When using the extension i expected to see input box to specify maxItem (workitem and changeset as mentionned in your spec). But nothing is visible.
![capturegrn](https://user-images.githubusercontent.com/38126572/38409316-4669295a-3981-11e8-9ccc-57f7174dce7a.PNG)

### Steps to reproduce the problem
Install Extension
Create a Release
Add Task "Generate Release Notes" to the Release
Trying to configure MaxWorkItem/MaxChangeset

**Comment by rfennell** [comment]
I can't repeat this issue, and I am only using standard fields in the the task definition so there should be no reason why the text field for the two values (which both default to 50) should not be shown.

The task was tested on TFS 2017 so it should not be an issue.mI have also retested on TFS 2018

You could try removing and re-adding the extension as I have seen caching issues in the past

**Comment by Bubleguy** [comment]
I removed and re-added with the same symptom. I even removed the "crossplatfrom version" just in case.

Maybe in the TFS 2015 version, the type "integer" is not understood in your config 

```{
      "name": "maxWi",
      "type": "integer",
      "label": "Maximum Work Items to return",
      "defaultValue": "50",
```
I don't know which language is used behind the scene, maybe "Int16" would have work ;)

Anyway, as the default 50 number seems to be sufficient by now, you can close this issue... or keep it opened for other people comments. Up to you.

Thanks for your good work.

**Comment by rfennell** [comment]
OK, thanks for the update. I don't propose to go back to TFS 2015 support (extensions where very new then).

Hope you get budget to upgrade to TFS 2018 or VSTS soon.

**Comment by Bubleguy** [comment]
My comment above is wrong the version 15.117.26714.0 is for TFS **2017 Update 2 RTM** (and not 2015)
https://blogs.msdn.microsoft.com/tfssetup/2013/11/21/what-version-of-team-foundation-server-do-i-have/

Sorry for that mistake.

**Comment by rfennell** [comment]
Still not much I can do, sounds like a local issue as I cannot repeat the problem

**Comment by Bubleguy** [comment]
No pb, it's fine. I'll investigate with my team
