### ISSUE TITLE
Provide default VERSION tag option for .NETCore Versioner 

### ISSUE THREAD

**Issue by rfennell** [rfennell/vNextBuild#302]
This is based on @deadlydog comment in #298 - adding a new issue to make tracking easier

### VSTS Extension you are using
Manifest versioning - DOTNETCore

### Expected behaviour and actual behaviour
From #298...

> It would make sense to add another boolean checkbox of Add Version field if missing to make it clear what the extension is doing, but I would also recommend that it be enabled by default.
> I know there's also the workaround you mentioned of:
>         Add an empty version element to the .csproj, and then add the VERSION tag to the task's field property.
> The problem I have with both the workaround and adding the new boolean field (and not having it enabled by default) is that your task won't do what people expect it to do. If I create a brand new vanilla .Net Core application, the version element is not added to the .csproj by default. So if I then used your extension and simply added it to my build process without making any changes to it, it wouldn't do anything. This would be confusing to users, and I think would result in more bug/issue reports. However, if you do add the new Add Version field if missing checkbox AND have it enabled by default, then your task would work as people would expect when used on a vanilla .Net Core application.
> 
>

**Comment by deadlydog** [comment]
Any ETA on this one @rfennell ?

**Comment by rfennell** [comment]
Probably next on the list, bugs allowing in other extensions. But I no timescale depends on how much time I have for 'free time, home projects'

Happy to consider PRs

**Comment by rfennell** [comment]
Shipped as 1.38.2

**Comment by rfennell** [comment]
This fix introduced a horrible regression

**Comment by rfennell** [comment]
Looks like I screwed up a merge at the end of PR and lost the #296 changes

I have done a new release 1.39.1 that should correct the issues reported in #323 #322 #302, it is PR #325 

Please reopen if I have not fixed the problem

My deepest apologies for such a stupid regression issue, all down to human error. The PR is obviously the part of the process that is not automated as part of  CI/CD pipeline
