### ISSUE TITLE
Error running the VSTS Generate Release Notes Build Task - Cannot bind argument to parameter 'Message' because it is null.

### ISSUE THREAD

**Issue by michaelmowry** [rfennell/vNextBuild#303]
### VSTS Extension you are using
Generate Release Notes Build Task

### Where are you running it?
VSTS

### Version of Extension/Task
Latest (2.21.3)

### Expected behaviour and actual behaviour
Running the build task give the following error: Cannot bind argument to parameter 'Message' because it is null.

Verbose logs provided below:

******************************************************************************
Starting: GenerateReleaseNotes
******************************************************************************
==============================================================================
Task         : Generate Release Notes
Description  : Generates a release notes file in a format of your choice
Version      : 2.21.3
Author       : Black Marble
Help         : Version: 2.21.3. [More Information](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes%20-Tasks/)
==============================================================================
Preparing task execution handler.
Executing the powershell script: C:\Agents\convbcprgitstg1.1\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.21.3\GenerateReleaseNotes.ps1
PowerShellHandler.Execute - AddCommand(C:\Agents\convbcprgitstg1.1\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.21.3\GenerateReleaseNotes.ps1)
PowerShellHandler.Execute - Add inputParameters
PowerShellHandler.Execute - AddParameter(outputfile=C:\Agents\convbcprgitstg1.1\_work\3\a\ReleaseNotes.htm)
PowerShellHandler.Execute - AddParameter(outputVariableName=)
PowerShellHandler.Execute - AddParameter(templateLocation=File)
PowerShellHandler.Execute - AddParameter(templatefile=\\CONVBCPRGITSTG1\Tools\Resources\build-basic-template.htm)
PowerShellHandler.Execute - AddParameter(inlinetemplate=)
PowerShellHandler.Execute - AddParameter(usedefaultcreds=false)
PowerShellHandler.Execute - AddParameter(emptySetText=None)
PowerShellHandler.Execute - AddParameter(generateForOnlyPrimary=False)
PowerShellHandler.Execute - AddParameter(generateForCurrentRelease=True)
PowerShellHandler.Execute - AddParameter(overrideStageName=)
PowerShellHandler.Execute - AddParameter(maxWi=50)
PowerShellHandler.Execute - AddParameter(maxChanges=50)
PowerShellHandler.Execute - AddParameter(appendToFile=False)
PowerShellHandler.Execute - AddParameter(showParents=False)
PowerShellHandler.Execute - AddParameter(wiFilter=)
PowerShellHandler.Execute - AddParameter(wiStateFilter=)
PowerShellHandler.Execute - AddParameter(unifiedList=False)
PowerShellHandler.Execute - Invoke
Loading module from path 'C:\Agents\convbcprgitstg1.1\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.21.3\GenerateReleaseNotes.psm1'.
Loading module from path 'C:\Agents\convbcprgitstg1.1\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.21.3\Get-CallerPreference.ps1'.
Dot-sourcing the script file 'C:\Agents\convbcprgitstg1.1\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.21.3\Get-CallerPreference.ps1'.
	 public enum Mode
	 {
			BODY,
			WI,
			CS,
			BUILD
	 }
Exporting function 'Get-CallerPreference'.
Exporting function 'Use-SystemWebProxy'.
Exporting function 'Get-BuildWorkItems'.
Exporting function 'Get-BuildChangeSets'.
Exporting function 'Get-Detail'.
Exporting function 'Get-Build'.
Exporting function 'Get-BuildsByDefinitionId'.
Exporting function 'Get-ReleaseDefinitionByName'.
Exporting function 'Get-Release'.
Exporting function 'Get-BuildReleaseArtifacts'.
Exporting function 'ConvertFrom-JsonUsingDOTNET'.
Exporting function 'Expand-Tree'.
Exporting function 'Add-Space'.
Exporting function 'Invoke-GetCommand'.
Exporting function 'Render'.
Exporting function 'Get-Template'.
Exporting function 'Get-Mode'.
Exporting function 'Add-StackItem'.
Exporting function 'Invoke-Template'.
Exporting function 'Get-BuildDataSet'.
Exporting function 'Get-ReleaseByDefinitionId'.
Importing function 'Add-Space'.
Importing function 'Add-StackItem'.
Importing function 'ConvertFrom-JsonUsingDOTNET'.
Importing function 'Expand-Tree'.
Importing function 'Get-Build'.
Importing function 'Get-BuildChangeSets'.
Importing function 'Get-BuildDataSet'.
Importing function 'Get-BuildReleaseArtifacts'.
Importing function 'Get-BuildsByDefinitionId'.
Importing function 'Get-BuildWorkItems'.
Importing function 'Get-CallerPreference'.
Importing function 'Get-Detail'.
Importing function 'Get-Mode'.
Importing function 'Get-Release'.
Importing function 'Get-ReleaseByDefinitionId'.
Importing function 'Get-ReleaseDefinitionByName'.
Importing function 'Get-Template'.
Importing function 'Invoke-GetCommand'.
Importing function 'Invoke-Template'.
Importing function 'Render'.
Importing function 'Use-SystemWebProxy'.
Using system web proxy.
collectionUrl = [https://companyname.visualstudio.com/]
teamproject = [VBC]
releaseid = []
releasedefid = []
stageName = []
overrideStageName = []
buildid = [15155]
builddefname = [companyname.Legacy.Libraries-CI]
releasedefname = []
buildnumber = [1.0.0.25]
outputVariableName = []
generateForOnlyPrimary = [False]
generateForCurrentRelease = [True]
maxWi = [50]
maxChanges = [50]
showParents =[False]
wiFilter = []
wiStateFilter = []
appendToFile = [False]
In Build mode
Getting build details for BuildID [15155]
Loading module from path 'C:\Agents\convbcprgitstg1.1\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.LegacySDK.dll'.
Importing cmdlet 'Invoke-ResultPublisher'.
Importing cmdlet 'Publish-TestResults'.
Importing cmdlet 'Add-BuildArtifactLink'.
Importing cmdlet 'Add-BuildAttachment'.
Importing cmdlet 'Convert-String'.
Importing cmdlet 'Copy-BuildArtifact'.
Importing cmdlet 'Get-JavaDevelopmentKitPath'.
Importing cmdlet 'Get-MSBuildLocation'.
Importing cmdlet 'Get-ServiceEndpoint'.
Importing cmdlet 'Get-TaskVariable'.
Importing cmdlet 'Get-TfsClientCredentials'.
Importing cmdlet 'Get-ToolPath'.
Importing cmdlet 'Get-VisualStudioPath'.
Importing cmdlet 'Get-VssConnection'.
Importing cmdlet 'Invoke-Ant'.
Importing cmdlet 'Invoke-BatchScript'.
Importing cmdlet 'Invoke-Maven'.
Importing cmdlet 'Invoke-MSBuild'.
Importing cmdlet 'Invoke-Tool'.
Importing cmdlet 'Invoke-VSTest'.
Importing cmdlet 'Publish-BuildArtifact'.
Importing cmdlet 'Register-XamarinLicense'.
Importing cmdlet 'Unregister-XamarinLicense'.
Importing cmdlet 'Get-X509Certificate'.
Importing cmdlet 'Invoke-DeployTestAgent'.
Importing cmdlet 'Invoke-RunDistributedTests'.
Importing cmdlet 'Invoke-BlockEnvironment'.
Importing cmdlet 'Copy-FilesToAzureBlob'.
Importing cmdlet 'Copy-FilesToTargetMachine'.
Importing cmdlet 'Copy-ToAzureMachines'.
Importing cmdlet 'Remove-Environment'.
Importing cmdlet 'Remove-EnvironmentResources'.
Importing cmdlet 'Complete-EnvironmentOperation'.
Importing cmdlet 'Complete-EnvironmentResourceOperation'.
Importing cmdlet 'Complete-ResourceOperation'.
Importing cmdlet 'Get-Environment'.
Importing cmdlet 'Get-EnvironmentProperty'.
Importing cmdlet 'Get-EnvironmentResources'.
Importing cmdlet 'Get-ExternalIpAddress'.
Importing cmdlet 'Get-ParsedSessionVariables'.
Importing cmdlet 'Get-ProviderData'.
Importing cmdlet 'Invoke-EnvironmentOperation'.
Importing cmdlet 'Invoke-ResourceOperation'.
Importing cmdlet 'Invoke-PsOnRemote'.
Importing cmdlet 'New-OperationLog'.
Importing cmdlet 'Copy-FilesToRemote'.
Importing cmdlet 'Register-Environment'.
Importing cmdlet 'Register-EnvironmentDefinition'.
Importing cmdlet 'Register-Provider'.
Importing cmdlet 'Register-ProviderData'.
Importing cmdlet 'Invoke-UnblockEnvironment'.
Importing cmdlet 'Add-TaskIssue'.
Importing cmdlet 'Complete-Task'.
Importing cmdlet 'Find-Files'.
Importing cmdlet 'Get-LocalizedString'.
Importing cmdlet 'Set-TaskProgress'.
Importing cmdlet 'Set-TaskVariable'.
Importing cmdlet 'Write-TaskDetail'.
Importing cmdlet 'Enable-CodeCoverage'.
Importing cmdlet 'Publish-CodeCoverage'.
Exporting cmdlet 'Add-BuildArtifactLink'.
Exporting cmdlet 'Add-BuildAttachment'.
Exporting cmdlet 'Convert-String'.
Exporting cmdlet 'Copy-BuildArtifact'.
Exporting cmdlet 'Get-JavaDevelopmentKitPath'.
Exporting cmdlet 'Get-MSBuildLocation'.
Exporting cmdlet 'Get-ServiceEndpoint'.
Exporting cmdlet 'Get-TaskVariable'.
Exporting cmdlet 'Get-TfsClientCredentials'.
Exporting cmdlet 'Get-ToolPath'.
Exporting cmdlet 'Get-VisualStudioPath'.
Exporting cmdlet 'Get-VssConnection'.
Exporting cmdlet 'Invoke-Ant'.
Exporting cmdlet 'Invoke-BatchScript'.
Exporting cmdlet 'Invoke-Maven'.
Exporting cmdlet 'Invoke-MSBuild'.
Exporting cmdlet 'Invoke-Tool'.
Exporting cmdlet 'Invoke-VSTest'.
Exporting cmdlet 'Publish-BuildArtifact'.
Exporting cmdlet 'Register-XamarinLicense'.
Exporting cmdlet 'Unregister-XamarinLicense'.
Exporting cmdlet 'Get-X509Certificate'.
Processed: ##vso[task.setprogress value=-1;]
Getting up to 50 associated work items for build [15155]
Found 0 WI directly associated with build
Running in directly associated WI only mode
Getting up to 50 associated changesets/commits for build [15155]
Using template mode [File]
Loading template file [\\machinename\Tools\Resources\build-basic-template.htm]
Processing template
There are [1] builds to process
**RENDER ERROR: cannot process [ <td id="LC3" class="blob-code blob-code-inner js-file-line">&lt;<span class="pl-ent">b</span>&gt;Build started&lt;/<span class="pl-ent">b</span>&gt; : $(&quot;{0:dd/MM/yy HH:mm:ss}&quot; -f [datetime]$build.startTime) &lt;<span class="pl-ent">br</span>&gt; </td>]
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.**
Processed: ##vso[task.logissue type=error;]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Render(Closure , FunctionContext )
**RENDER ERROR: cannot process [ <td id="LC7" class="blob-code blob-code-inner js-file-line">&lt;<span class="pl-ent">li</span>&gt; &lt;<span class="pl-ent">b</span>&gt;$($widetail.fields.&#39;System.WorkItemType&#39;) $($widetail.id)&lt;/<span class="pl-ent">b</span>&gt; [Assigned by: $($widetail.fields.&#39;System.AssignedTo&#39;)] $($widetail.fields.&#39;System.Title&#39;) </td>]
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.**
Processed: ##vso[task.logissue type=error;]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Render(Closure , FunctionContext )
Writing to output file [C:\Agents\convbcprgitstg1.1\_work\3\a\ReleaseNotes.htm].
Skipping setting output variable name as parameter was not set.
PowerShell script completed with 2 errors.
******************************************************************************
Finishing: GenerateReleaseNotes
******************************************************************************

### Steps to reproduce the problem
Output File = $(Build.ArtifactStagingDirectory)\ReleaseNotes.htm
Template Location = File
Template File = $(BuildAgentToolsDirectory)\Resources\build-basic-template.htm

**Comment by rfennell** [comment]
This issue is usually down to a typo in the template. The lines it so failing to render look OK to me at first look.

I would suggest removing the offending lines, make sure the task work Ok then add the lines back field by field to isolate the issue.

**Comment by eFloh** [comment]
Same problem here, without changing the template.
Worked well in Version: 2.19.2, broken in Version 2.21.3.
Hints: System language here is set to german.

Found a Resolution: change `$build.startTime` to `$Build.StartTime` (only different casing!)

**Comment by michaelmowry** [comment]
I had $build.finishTime in my custom template, but changing it to $Build.FinishTime did not fix the issue.

**Comment by rfennell** [comment]
If the task is being used in a build you can't use finish time, it is null as the build has not finished

**Comment by michaelmowry** [comment]
Ok just tried this again with the build-dump-template.md and it appears that the error is related to the workitems and changesets being 0 (as I am testing a build over and over without making changes).  Could that be the issue and is it possible to check for >0 before processing the work items and changesets?

# Release notes for build $defname  
**build**: $($build)   


***Note** that if the is a single associated item then then size is empty, but the item is returned  
If there are multiple associated items then the size is >0  but you need to use an index to see each item*   
****workitems:** [Size $($workitems.length)] $($workitems)     
**workitems:** [Size $($workitems.length)] $($workitems[0])     

**changesets:**[Size $($changesets.length)] $($changesets)     
**changesets:**[Size $($changesets.length)] $($changesets[0])**  
  
## Associated work items (Dump of all fields)  
@@WILOOP@@  
* **widetail:** $($widetail)
* **widetail.fields:** $($widetail.fields)  
* **widetail.links:** $($widetail.fields)  
@@WILOOP@@  
  
## Associated change sets/commits (Dump of all fields) 
@@CSLOOP@@  
* **csdetail:** $($csdetail)    
@@CSLOOP@@

**Comment by michaelmowry** [comment]
> workitems: [Size $($workitems.length)] $($workitems)
> workitems: [Size $($workitems.length)] $($workitems[0])
> 
> changesets:[Size $($changesets.length)] $($changesets)
> changesets:[Size $($changesets.length)] $($changesets[0])

These lines give the "Cannot bind argument to parameter 'Message' because it is null" error whenever there are 0 work items or changesets in the build.  It looks like those lines should be wrapped with a check for existence.

**Comment by rfennell** [comment]
@michaelmowry yes you are correct. The issue behind the scenes is that I parse each line in the template line by line, and I do it by just passing the line into PowerShell. The important fact is I don't inspect the contents. This means I have no means to check the whether to run any given line based on the size of the arrays or not.

This is a limitation I don't plan to fix as it would require a major rework in the way the template is parsed.

I just don't use .length values in my real templates

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
