### ISSUE TITLE
Generate Release Notes Build Task - Filter by specific work item field

### ISSUE THREAD

**Issue by bo-stig-christensen** [rfennell/vNextBuild#304]
Is there already functionality to add filtering of release notes work items based on an arbitrary field?

Using GitFlow, I would like to look at any work items associated with commits since my last release on Master branch. This is in place already.
What I would like is to filter the work items additionally by any field, e.g. "Release Note" (a string field containing a release note text for the current work item). - If the "Release Note" field is filled, I would use that field in the release notes template as well.

An alternative (but also more advanced) solution would be to be able to provide a base query, inside which I would define my "Release Note must contain data" filter, or any other filter for that matter. - On top of this would be the standard filtering done by the extension already.

This would provide a very granular control over which work items hit the release notes. - Not all work items and tasks are meant for release notes ;-)

**Comment by rfennell** [comment]
The request for filtering is an old one, see #35 Because each line of the template is resolved at a time cross line logic is not an issue, also there is a concern over potential security issues. 

Hence it has not been something I have been planning to look at as #35 mentions

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
