### ISSUE TITLE
Cannot generate release notes for different stage (override stage name)

### ISSUE THREAD

**Issue by marco-gallinari** [rfennell/vNextBuild#315]
### VSTS Extension you are using
Generate Release Notes XPlatform

### Where are you running it?
VSTS

### Version of Extension/Task
2.0.33

### Expected behaviour and actual behaviour
I am not able to build release notes against production stage during dev release. 
Release note is always generating from previous succesfully release on the same stage.

**Comment by rfennell** [comment]
Oops, looked like that was missed in testing, I will re-check with your PR

**Comment by rfennell** [comment]
Released as 2.1.1

**Comment by rfennell** [comment]
Thanks for the PR, that and an automated CI/CD pipeline makes fixing issue much quicker
