### ISSUE TITLE
Note fail on the first run

### ISSUE THREAD

**Issue by baileyjs78** [rfennell/vNextBuild#319]
### VSTS Extension you are using
Generate Release Notes based on Release Comparision API

### Where are you running it?
On Prem TSF 2017-latest update

### Version of Extension/Task
Version: 2.1.1

### Expected behaviour and actual behaviour
When setting up a release for a branc new project, the ext failed
It was not able to get a value for compareReleaseDetails.name
There were no other releases to compare with
I would expect the extension to either gracefully exit or show all changes

### Steps to reproduce the problem
Create a branch new pipeline, or delete all other releases

**Comment by rfennell** [comment]
Yes that sound a bug, I will need to look to create a repo of the problem

**Comment by rfennell** [comment]
Got a repo, I will look into a fix that makes this use case robust

**Comment by rfennell** [comment]
Fixed in 2.2.2
