### ISSUE TITLE
Update Regex Check in ApplyBuildVersionToAppx.ps1

### ISSUE THREAD

**Issue by technicallyerik** [rfennell/vNextBuild#32]
Currently:
`$VersionRegex = "\d+\.\d+\.\d+\.\d+"`

However, the restrictions for Appx versions from Microsoft are more strict:

`(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])(\.(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])){3}`

**Comment by rfennell** [comment]
Thanks for that, just published the revised regex in 1.5.1

**Comment by rfennell** [comment]
Published as 1.5.1
