### ISSUE TITLE
VSTS Pester test extension does not log Parameters being passed to it in scriptfolder property

### ISSUE THREAD

**Issue by bergmeister** [rfennell/vNextBuild#320]
### VSTS Extension you are using
VSTS Pester test extension

### Where are you running it?
VSTS, agent on-premise

### Version of Extension/Task
v7* (latest)

### Expected behaviour and actual behaviour

When I specify the `scriptfolder` property as `@{Path='.\tests\script.tests.ps1'; Parameters=@{fancypants="$(SecretValue)"; port=$port}; Path='.\tests\script2.tests.ps1'; Parameters=@{otherparam="$(DifferentValue)"}}`
then I need to have the value of parameters logged for debugging

The test script path gets logged by Pester itself but no the Parameters that are passed to it. This should probably also be improved in Pester itself when using the `-Verbose` option

**Comment by ChrisLGardner** [comment]
I'll have a look at this, it should be a pretty easy improvement to make to the task.

**Comment by ChrisLGardner** [comment]
Digging into this and it looks like we do log it already but as we're using Write-Verbose to do so then you need to set the build variable System.Debug to True for this to surface. Annoyingly this will also dump a bunch of Import-Module verbose information into the log file as well but I'm looking into ways to reduce that (-Verbose:$False doesn't help).

At the moment it's all put into a single line of verbose output but I'll try to break it up a bit more and give some structure to it, possibly as part of the converting to a hashtable.

**Comment by bergmeister** [comment]
@ChrisLGardner Ok, thanks for looking this. May I suggest using `Write-Verbose -Verbose` in this case because I rarely use `system.debug` in VSTS because it is too verbose for me. It is a known issue of Windows PowerShell (but not PowerShell Core) that `-Verbose:$False` does not work for `Import-Module`: https://github.com/PowerShell/PowerShell/issues/4143

**Comment by ChrisLGardner** [comment]
We're already using Write-Verbose -Verbose but it is very flaky with when it actually displays the output correctly. It seems to work fine in releases but not in builds.

I'd seen some notes about either enabling it to work correctly but I haven't been able to find those in a while. I'm tempted to swap over to Write-Host since it's now fixed in PSv5+ since that will always show in the log files correctly.

**Comment by ChrisLGardner** [comment]
Released as part of 7.2.1

**Comment by bergmeister** [comment]
@ChrisLGardner Thanks. I can confirm this is fixed now
