### ISSUE TITLE
Replaced LangVersion

### ISSUE THREAD

**Issue by Benni1508** [rfennell/vNextBuild#322]
### VSTS Extension you are using
VersionDotNetCoreAssembliesTask

### Where are you running it?
VSTS

### Version of Extension/Task
1.38.2

### Expected behaviour and actual behaviour
Since latest Version the Task replaced the Tag <LangVersion>. 
This is a big issue because this is a Tag from VisualStudio to select the C# Language Version, after replace the build fails.

```
2018-05-08T14:54:58.3499684Z Checking if any version fields to update
2018-05-08T14:54:58.3504533Z Existing Tag: <LangVersion>latest</LangVersion>
2018-05-08T14:54:58.3504678Z Replacement Tag: <LangVersion>0.2.4.9190</LangVersion>
2018-05-08T14:54:58.3508696Z Existing Tag: <LangVersion>latest</LangVersion>
2018-05-08T14:54:58.3508952Z Replacement Tag: <LangVersion>0.2.4.9190</LangVersion>
```
### Steps to reproduce the problem
Add the folowing Tag to your *.csproj File
```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
```

**Comment by rfennell** [comment]
Looks like I introduced a bug with 1.38.2 looking into it ASAP

**Comment by rfennell** [comment]
Looks like I screwed up a merge at the end of PR and lost the #296 changes

I have done a new release 1.39.1 that should correct the issues reported in #323 #322 #302, it is PR #325 

Please reopen if I have not fixed the problem

My deepest apologies for such a stupid regression issue, all down to human error. The PR is obviously the part of the process that is not automated as part of  CI/CD pipeline
