### ISSUE TITLE
Same again, builds are broken

### ISSUE THREAD

**Issue by EricSch** [rfennell/vNextBuild#323]
see Issue #296, now in Version 1.38.2. No more checks for .NET Core projects files?

**Comment by rfennell** [comment]
Looks like I introduced a bug with 1.38.2 looking into it ASAP

**Comment by rfennell** [comment]
Looks like I screwed up a merge at the end of PR and lost the #296 changes

I have done a new release 1.39.1 that should correct the issues reported in #323 #322 #302, it is PR #325 

Please reopen if I have not fixed the problem

My deepest apologies for such a stupid regression issue, all down to human error. The PR is obviously the part of the process that is not automated as part of  CI/CD pipeline
