### ISSUE TITLE
Running "StyleCop Runner Task" on a hosted macOS agent

### ISSUE THREAD

**Issue by munkii** [rfennell/vNextBuild#326]
### VSTS Extension you are using
StyleCop, StyleCop Runner Task

### Where are you running it?
VSTS

### Version of Extension/Task
2.3.2

### Expected behaviour and actual behaviour
I don't think it will run on the "Hosted macOS Preview" agent. No surprise to be fair as i'm guessung you've not needed to do a Xamarin iOS  build. 

The error is :

"_A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details_"

### Steps to reproduce the problem

Add the StyleCop task to a build that uses the "Hosted macOS Preview" agent

**Comment by rfennell** [comment]
The basic issue you have here is that StyleCop is a full .NET framework tool. This task only wrappers a command line version using the StyleCop DLLs. Full .NET framework is not available for Linux or MacOS, so there is no point writing the any tasks that target anything other than Windows for StyleCop.

My best suggestion is to look at [SonarQube (for on prem) or SonarCloud (hosted) ](https://www.sonarqube.org/). This can be integrated with VSTS build using the [SonarQube extension](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube) which is [written open source in Typescript](https://github.com/SonarSource/sonar-scanner-vsts/tree/master/extensions/sonarqube/tasks/analyze/new). 

SonarQube's C# analysis tools are based around the Roslyn engine so I think should work cross platform on .NET core, but I have not tested it.

**Comment by munkii** [comment]
You can run StyleCop on the Mac but the only situations I've heard of that are supported are within Visual Studio for Mac or Xamarin Studio via AddIns. I'm guessing they are relying on the IDEs parsing of the code rather than a command line interface to the StyleCop dll. Sound likely?

**Comment by rfennell** [comment]
I think  what you talk about is based around [this StyleCopAnalyzers project](https://github.com/DotNetAnalyzers/StyleCopAnalyzers).

Sorry I have not keep up to date on that project as we have decided to move to SonarQube. I had not planned to make any changes to my extension, as I felt StyleCop in its old form was on its way out, with the move to Roylyn

**Comment by munkii** [comment]
So do you use SonarQube to enforce a coding standard in a similar way to how StyleCop would have been used? I've never used SonarQube. Thanks
