### ISSUE TITLE
405 - Method Not Allowed - changing variable

### ISSUE THREAD

**Issue by xlone** [rfennell/vNextBuild#33]
Below is the output from the log of my build. Some of the variables are not getting populated, like releaseid and builddefid. 

2016-08-11T15:40:11.6200827Z Executing the powershell script: C:\Builds\Agent2\tasks\BuildVariableTask\1.0.15\BuildVariableTask.ps1

2 
2016-08-11T15:40:17.7816092Z ##[debug]collectionUrl = [http:/tfs:8080/tfs/MyProjects/]

3 
2016-08-11T15:40:17.7816092Z ##[debug]teamproject = [My Suite]

4 
2016-08-11T15:40:17.7816092Z ##[debug]releaseid = []

5 
2016-08-11T15:40:17.7816092Z ##[debug]builddefid = []

6 
2016-08-11T15:40:17.7816092Z ##[debug]Mode is Prime

7 
2016-08-11T15:40:20.8284952Z ##[debug]Getting Build Definition  

8 
2016-08-11T15:40:21.3128784Z ##[debug]Current value of variable [PatchVersion] is []

9 
2016-08-11T15:40:21.3128784Z ##[debug]Manually updating variable

10 
2016-08-11T15:40:21.4378760Z ##[error]The property 'value' cannot be found on this object. Verify that the property exists and can be set.

11 
2016-08-11T15:40:21.4378760Z ##[debug]Setting variable [PatchVersion] to value []

12 
2016-08-11T15:40:21.5003775Z ##[debug]Updating Build Definition  for http://tfs.software-answers.com:8080/tfs/SoftwareAnswersProjects//ProgressBook Suite

13 
2016-08-11T15:40:22.5003911Z ##[error]Exception calling "UploadString" with "3" argument(s): "The remote server returned an error: (405) Method Not Allowed."

I am using TFS 2015, update 3, on premises. Any idea how to resolve this error?

**Comment by rfennell** [comment]
Can I just check, are you using this task within a Build or a Release pipeline - it has only been tested within a release. I should probably alter the manifest to make sure it only appears in release.

It picks up all the variables from environment variables, so can't see why it should not work otherwise

**Comment by xlone** [comment]
I am using it in a build.  I looked through the list of variables you are using, and it looked like some of them no longer exist in TFS environment.  It looks like the BUILD_BUILDDEFINITIONID

**Comment by rfennell** [comment]
It was designed for use in a Release - my mistake in the manifest allowed it to be used in a build

But you make a valid point, there are cases you might want to use it in a build. It should only be an case of altering the environment variables read.

However, I would ask why you are not using a release? Our normal pattern is to build a nuget package in a build, but then publish/deploy it to the nuget server with a release pipeline. Feels like a nice separation even if you automatically trigger the release from the build.

**Comment by xlone** [comment]
I will discuss that idea with the team. We were wanting an automatic way of versioning or nuget packages. This includes our assemblies as well. I don't think we can version our assemblies during the release.

Get Outlook for iOS




On Thu, Aug 11, 2016 at 4:00 PM -0400, "Richard Fennell" <notifications@github.com> wrote:





It was designed for use in a Release - my mistake in the manifest allowed it to be used in a build

But you make a valid point, there are cases you might want to use it in a build. It should only be an case of altering the environment variables read.

However, I would ask why you are not using a release? Our normal pattern is to build a nuget package in a build, but then publish/deploy it to the nuget server with a release pipeline. Feels like a nice separation even if you automatically trigger the release from the build.

**Comment by rfennell** [comment]
If it helps the way we do it is
**Build (a CI build triggered on every checkin)**
1. Get files
2. Version the assemblyinfo.cs files with the build number using a [custom task](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-Versioning-Task)
3. Build the solution
4. Run any unit tests we have
5.. Create the nuget package - setting the package version as a parameter
6. Publish the nuget file as the build output artifact
**Release (usually manually triggered but could be automatic)**
1. Publish to our nuget server's preview/beta feed
2. Manual approval
3. Publish to our nuget server's production feed

**Comment by rfennell** [comment]
To avoid this confusion in the future I am pushing out a new release that stops the tasks appearing as being available for builds

**Comment by rfennell** [comment]
Just written the blog post, thought it may help http://blogs.blackmarble.co.uk/blogs/rfennell/post/2016/08/16/Experiences-versioning-related-sets-of-NuGet-packages-within-a-VSTS-build

**Comment by xlone** [comment]
Thanks for the link. It was a good read and gave me some ideas.

Get Outlook for iOS




On Tue, Aug 16, 2016 at 7:44 AM -0400, "Richard Fennell" <notifications@github.com> wrote:





Just written the blog post, thought it may help http://blogs.blackmarble.co.uk/blogs/rfennell/post/2016/08/16/Experiences-versioning-related-sets-of-NuGet-packages-within-a-VSTS-build
