### ISSUE TITLE
Logging unclear within VersionDotNetCoreAssembliesTask

### ISSUE THREAD

**Issue by philmh-isams** [rfennell/vNextBuild#335]
### VSTS Extension you are using
VersionDotNetCoreAssembliesTask

### Where are you running it?
VSTS

### Version of Extension/Task
Latest

### Expected behaviour
Supplied version applied to csproj files, and therefore to DLLs.

### Actual behaviour
Version was always set as 1.0.0.0 on all DLLs.

### Steps to reproduce the problem
Create a C# project without an AssemblyInfo.cs and no version properties within the .csproj file, and GenerateAssemblyInfo must be true.

Define the step as follows:
```
steps:
- task: richardfennellBM.BM-VSTS-Versioning-Task.Version-DotNetCoreAssemblies-Task.VersionDotNetCoreAssemblies@1
  displayName: Version .NET Core Assemblies
  inputs:
    Path: '$(Build.SourcesDirectory)/ProjectToVersion'
```

When the build runs the logging is as follows:
```
2018-06-25T09:08:04.1363194Z Checking if any version fields to update
2018-06-25T09:08:04.1366206Z Processing Field Version
2018-06-25T09:08:04.1367099Z Processing Field VersionPrefix
2018-06-25T09:08:04.1367538Z Processing Field AssemblyVersion
2018-06-25T09:08:04.1368766Z ProjectToVersion.csproj - version applied
```

However, the version is not applied because addDefault is true, so I propose the following; which I have in a local commit if you wish to grant me access:
```
export function ProcessFile(file, field, newVersion, addDefault = false) {
	var isVersionApplied: any = false;
    // Check that the field to update is present
    if (field && field.length > 0) {
        UpdateSingleField(file, field, newVersion);
		isVersionApplied = true;
    } else {
        console.log(`Checking if any version fields to update`);
        var filecontent = fs.readFileSync(file);
        fs.chmodSync(file, "600");
        // We only need to consider the following fields
        let versionFields = ["Version", "VersionPrefix", "AssemblyVersion"];
        let content: string = filecontent.toString();
        var hasUpdateFields: any = false;
        versionFields.forEach(element => {
            console.log(`Processing Field ${element}`);
            const csprojVersionRegex = `(<${element}>)(.*)(<\/${element}>)`;
            var regexp = new RegExp(csprojVersionRegex, "gmi");
            let matches;
            while ((matches = regexp.exec(content)) !== null) {
                var existingTag1: string = matches[0];
                console.log(`Existing Tag: ${existingTag1}`);
                var replacementTag1: string = `${matches[1]}${newVersion}${matches[3]}`;
                console.log(`Replacement Tag: ${replacementTag1}`);
                content = content.replace(existingTag1, replacementTag1);
                hasUpdateFields = true;
            }
        });
        if (hasUpdateFields === true) {
            fs.writeFileSync(file, content);
			isVersionApplied = true;
        } else {
            if (addDefault === true) {
                console.log(`No version fields present, so add a Version field`);
                UpdateSingleField(file, "Version", newVersion);
				isVersionApplied = true;
            } else {
                console.log(`No version fields present, version field ignored because 'addDefault' is false`);
			}
        }
    }
	if (isVersionApplied) {
		console.log (`${file} - version applied`);
	} else {
		console.log (`${file} - version not applied`);
	}
}
```

**Comment by rfennell** [comment]
Thanks for digging into this, please submit the change as a PR and I will look into it

**Comment by philmh-isams** [comment]
Pushing to https://github.com/rfennell/vNextBuild
remote: Permission to rfennell/vNextBuild.git denied to philmh-isams.
fatal: unable to access 'https://github.com/rfennell/vNextBuild/': The requested URL returned error: 403

**Comment by ChrisLGardner** [comment]
You'll need to click the Fork button, make the changes on a branch there (or push them from your clone of this repo to the fork) and then make the PR from the fork.

Check out the Github docs on these:

[Pull Requests](https://help.github.com/articles/about-pull-requests/)
[Forks](https://help.github.com/articles/fork-a-repo/)

**Comment by rfennell** [comment]
I have accepted the PR, I made a change updating the extension readme, this is version 1.41.1

@ChrisLGardner  is currently making some changes to a different task in this extension package, so we will release the updated version 1.42.x once that is done

I will keep the issue open until that is done

**Comment by rfennell** [comment]
Should be released now
