### ISSUE TITLE
System.Management.Automation.ItemNotFoundException

### ISSUE THREAD

**Issue by matthewalbright** [rfennell/vNextBuild#355]
### VSTS Extension you are using
Generate release Notes

### Where are you running it?
VSTS

### Version of Extension/Task
2.*

### Expected behaviour and actual behaviour
Inline template works and allows the release notes to be generated in the md using the inline template format.

Instead, we are getting the following error when trying to use the inline template functionality:

System.Management.Automation.MethodInvocationException: Exception calling "Deserialize" with "2" argument(s): "Invalid JSON primitive: ." ---> System.ArgumentException: Invalid JSON primitive: .

System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.

PowerShell script completed with 2 errors.

### Steps to reproduce the problem
Use VSTS Extension

Display Name:
Generate release notes

Output File:
$(Agent.ReleaseDirectory)\releasenotes.md (also tried releasenotes.md)

Template Location:
InLine

Template:
<h1>Release notes for build $defname</h1>  
<b>Build Number</b>  : $($build.buildnumber)    <br>  
<br>  
<b>Source Branch</b> : $($Build.SourceBranch)  <br>  
<h3>Associated work items</h3>  
@@WILOOP@@  
<li> <b>$($widetail.fields.'System.WorkItemType') $($widetail.id)</b> [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
@@WILOOP@@  
<h3>Associated change sets/commits</h3>  
@@CSLOOP@@  
<li> <b>ID $($csdetail.changesetid)$($csdetail.commitid)</b> $($csdetail.comment)    
<hr>  
@@CSLOOP@@

Generate for only this release - true (checked)

**Comment by rfennell** [comment]
This type of problem is is usually found to be a typo in a template, but can't say I can see an obvious one.

I would suggest running with a basically empty template , maybe just the header block and add the fields back in one by one.

Also could you do a build with full debug , set the system.debug variable to true. It won't show that much more but will give an idea which call failed

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
