### ISSUE TITLE
Relase with No builds? Error

### ISSUE THREAD

**Issue by bbakermmc** [rfennell/vNextBuild#357]
### VSTS Extension you are using
Release Notes

### Where are you running it?
VSTS

### Version of Extension/Task
Current

### Steps to reproduce the problem
We use Gitflow - did a hotfix to master, triggered two builds, one on dev one on master.  Release then shows 0 builds?

output

Release notes for release Sonex - CI
@{url=apis/Release/releases/90; projectReference=System.Object[]; id=90; keepForever=False; name=Sonex Release-18; _links=System.Object[]; triggeringArtifactAlias=; definitionSnapshotRevision=1; artifacts=System.Object[]; releaseNameFormat=Sonex Release-$(rev:r); properties=System.Object[]; modifiedOn=2018-08-08T00:50:56.41Z; reason=manual; variables=System.Object[]; releaseDefinition=System.Object[]; tags=System.Object[]; createdOn=2018-08-08T00:50:56.41Z; description=; variableGroups=System.Object[]; status=active; modifiedBy=System.Object[]; logsContainerUrl=apis/Release/releases/90/logs; environments=System.Object[]; createdBy=System.Object[]}

Builds
0

Associated work items
None

Associated change sets/commits
@{comment=Merge tag 'AddIndexHintToAvailableRecordsQuery' into develop
Add Index Hint To Available Records Query AddIndexHintToAvailableRecordsQuery; url=apis/git/repositories/8e03ad2a-5800-4e1a-963d-788c21212337/commits/1e016ce99c834eb61e29bd0548142688b17c6674; _links=System.Object[]; treeId=9e102703f23d24c568799a2a5b86ca678855ab36; push=System.Object[]; parents=System.Object[]; author=System.Object[]; remoteUrl=commit/1e016ce99c834eb61e29bd0548142688b17c6674; commitId=1e016ce99c834eb61e29bd0548142688b17c6674; committer=System.Object[]}
* @{comment=Merge branch 'hotfix/AddIndexHintToAvailableRecordsQuery'; url=apis/git/repositories/8e03ad2a-5800-4e1a-963d-788c21212337/commits/917beec82845c03034bc4b014f8ca2736dd616c8; _links=System.Object[]; treeId=37bdd3e3270a9cac1c3d71824822f4df13494622; push=System.Object[]; parents=System.Object[]; author=System.Object[]; remoteUrl=commit/917beec82845c03034bc4b014f8ca2736dd616c8; commitId=917beec82845c03034bc4b014f8ca2736dd616c8; committer=System.Object[]}
* @{comment=Add Index Hint to CallListLoad List Admin queries; urlapis/git/repositories/8e03ad2a-5800-4e1a-963d-788c21212337/commits/f071b3c14884545e58ebabfeacb698a1ceff1ea7; _links=System.Object[]; treeId=37bdd3e3270a9cac1c3d71824822f4df13494622; push=System.Object[]; parents=System.Object[]; author=System.Object[]; remoteUrl=commit/f071b3c14884545e58ebabfeacb698a1ceff1ea7; commitId=f071b3c14884545e58ebabfeacb698a1ceff1ea7; committer=System.Object[]}

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
