### ISSUE TITLE
Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by NatarajanSivasankaran** [rfennell/vNextBuild#362]
### VSTS Extension you are using
Task         : StyleCop Runner by Black Marble
Description  : Black Marble's StyleCop test runner that use settings files in the project folders. (Using StyleCop 5.0.6419.0)
Version      : 2.3.2
Author       : Black Marble

### Where are you running it?
On Permission build agent

### Steps to reproduce the problem
If we entered the value for input 'Source File Folder' as '$(build.SourcesDirectory)' means it is working fine, but it will scan all files in all folders (All projects and solution), if we give filtered path as '$(build.SourcesDirectory)/Application/Project1/' meens we are getting error like below:

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'." ---> System.TypeLoadException: Could not load type 'log4net.Util.Serializer.ISerializerFactory' from assembly 'log4net.Ext.Json, Version=1.2.15.4226, Culture=neutral, PublicKeyToken=null'.

**Comment by rfennell** [comment]
Have you got a detailed error log (set a variable system.debug=true) so we can see how far it is getting.

The way the tool works is it hunts for a Stylecop settings file to use, working up the the tree from the start point. My guess is that using your project start point it find a file of the right name that is corrupt or invalid

**Comment by NatarajanSivasankaran** [comment]
Now it is working by given additional path which is having Stylecop.settings file, Thanks

**Comment by rfennell** [comment]
Glad you are unblocked
