### ISSUE TITLE
Allow PowerShell version task to extract version number from build number

### ISSUE THREAD

**Issue by ggirard07** [rfennell/vNextBuild#363]
### VSTS Extension you are using
`Version-PowerShellModule-Task`

### Where are you running it?
VSTS

### Version of Extension/Task
1.42.2

### Expected behaviour and actual behaviour
Many of the versioning tasks available in your extension are capable to extract a version number based on a regex from the build number. This is not the case of `Version-PowerShellModule-Task`.

### Steps to reproduce the problem
1. Create empty build pipeline.
2. In options tab, set Build Number as `$(BuildDefinitionName)-$(SourceBranchName)_1.0.$(date:yy)$(DayOfYear).$(Rev:r)`
3. Add `Version-PowerShellModule-Task` task to pipeline (with default value `$(Build.BuildNumber)` for `VersionNumber`).
4. Queue a new build.

**Comment by ChrisLGardner** [comment]
I'll have a look at this in the next few days. I'm not sure why I missed this functionality when I first implemented it.

**Comment by ChrisLGardner** [comment]
That should definitely be possible. I'll make sure I do it at the same time.

**Comment by ChrisLGardner** [comment]
Released as v2.0.x as it felt like a probably breaking change to include the Output Variable changes.
