### ISSUE TITLE
Pester Test Runner Build Task fails if PSGallery is not registered

### ISSUE THREAD

**Issue by thealmguy** [rfennell/vNextBuild#366]
### VSTS Extension you are using
Pester Test Runner Build Task

### Where are you running it?
TFS v2018 (16.122.27102.1)

### Version of Extension/Task
8.5.1

#### Expected:
The task to use the bundled 4.3.1 version of Pester, as per the description:

_Run Pester tests by either installing the latest version of Pester at run time (if possible) or using the version shipped with the task (4.3.1)
Version: 8.5.1._

#### Actual: 
The task attempted to find the latest version of Pester using PSGallery (which I remove on my servers in favour of an internal package management feed). This causes the task to error:

_Preparing task execution handler.
Executing the powershell script: E:\Agents\General-A01\_work\_tasks\Pester_31ef0033-64e3-4c55-b888-f446541474a6\8.5.1\Pester.ps1
Running in AMD64 PowerShell
Adding additional module path [] to $env:PSModulePath
**System.Exception: Unable to find repository 'PSGallery'. Use Get-PSRepository to see all available repositories.**
Running Pester from the folder [E:\Agents\General-A01\_work\15\s\Tests\Run-Tests.ps1] output sent to [E:\Agents\General-A01\_work\15\s\Test-Pester.XML]_

### Steps to reproduce the problem
Run _Unregister-PSRepository PSGallery_ on build host under the account that runs the build agent service
Run build with Pester Test Runner Build Task

**Comment by ChrisLGardner** [comment]
Would you rather it use the version provided or always download the latest version from whatever PS Repo it can?

Either should be reasonably simple fixes and I should be able to push out a new release in the next few days.

**Comment by thealmguy** [comment]
Either works in my scenario. If it looks for the latest version in any PSRepos available, that would be the more flexible option.

Thanks :)

**Comment by ChrisLGardner** [comment]
Released as part of 8.6.x

Let me know if it doesn't fix your issue.

**Comment by matthiascsg** [comment]
Good morning, 
I'm facing an issue with the 8.6.2 version of the task. 
### Pester.ps1 (line76)
The script is now getting the first PSRepository, assuming the first one is be PSGallery.

In my case, I have two other feeds registered. PSGallery is in third place. So when searching the Pester module in the first repository, I have the following error :

```##[error]System.Exception: No match was found for the specified search criteria and module name 'Pester'. Try Get-PSRepository to see all available registered module repositories.```

I went back to version 7.* in my build definition and it works fine. I also noted that version 8.5.1 was working fine. 

Can you look into that ?

Thank you,

--
Matt

**Comment by ChrisLGardner** [comment]
I should be able to add some logic in to find the repository where Pester is available and install from the first one of those. I'll see if I can find some time in the next few days to get that changed.

**Comment by matthiascsg** [comment]
> I should be able to add some logic in to find the repository where Pester is available and install from the first one of those. I'll see if I can find some time in the next few days to get that changed.

Thank you very much! Let me know if you need additional information.

Great extension 👍 

--
Matt

**Comment by ChrisLGardner** [comment]
@matthiascsg should be solved with version 8.7.2
