### ISSUE TITLE
Build Report

### ISSUE THREAD

**Issue by qyz01** [rfennell/vNextBuild#370]
I want to make a build report to get all work items and related check in under Epic->Feature->User Story->Bugs etc..
Is it possible to get all work items including their parent's information in each layer and related check in for a build rather than just loop out all work items and check in together? any sample?

**Comment by rfennell** [comment]
Not in the current logic, it would require a fairly major change as the APIs used only return a simple list.

It is not something I was planning to look, as focusing on other extensions at present. 

However happy to consider PRs.
