### ISSUE TITLE
Is it possible to just show the title of each commit?

### ISSUE THREAD

**Issue by Sundin** [rfennell/vNextBuild#371]
Is it possible to just show the title of each commit, i.e. just the first line of the commit message?

Also, it would be great if there would be documentation on what fields the `widetail`and `csdetail` objects do have.

### VSTS Extension you are using
Version 2.0 extension

### Where are you running it?
VSTS

**Comment by rfennell** [comment]
Just realized I am not sure if you are using the older PowerShell (Windows agent only works in builds and releases) or newer Node (Xplatform works only in releases) version of this extension

However, either way using something like [this](https://github.com/rfennell/vNextBuild/blob/master/SampleTemplates/GenerateReleaseNotes%20(Original%20Powershell%20based)/build-dump-template.md) (assuming PowerShell version, alter the format for Node as require) will just dump the whole of the CS or Wi object so you can see the fields

**Comment by Sundin** [comment]
Thanks for your answer. I tried dumping the whole object but all output I get is `[object Object]`.

I'm using the Xplatform version 2 in my release pipeline.

**Comment by rfennell** [comment]
Off the top of my head does a tostring() help?
