### ISSUE TITLE
Pester Extension Setup Script/Option

### ISSUE THREAD

**Issue by iainbrighton** [rfennell/vNextBuild#377]
### VSTS Extension you are using
Pester

### Where are you running it?
VSTS

### Version of Extension/Task
8.7.2

### Expected behaviour and actual behaviour
When dealing with PSSnapins (unfortunately we still have some 3rd party dependencies), they have to be loaded at the root/global scope and can't be added/imported within the `.tests.ps1` file. Multiple calls to `Add-PSSnapin` results in `Add-PSSnapin : An item with the same key has already been added.` errors being thrown, failing the tests.

The way around this is to remove the `Add-PSSnapin` calls from each test and run it in the root PowerShell scope - __before `Invoke-Pester` is called__. This results in them only being loaded once.

Can we have a way to run a scriptblock or command in the extension before the `Invoke-Pester` call? Some kind of setup step?

### Steps to reproduce the problem
N/A

**Comment by ChrisLGardner** [comment]
Released in 8.8.x
