### ISSUE TITLE
How to pass the version number to the next task

### ISSUE THREAD

**Issue by ridomin** [rfennell/vNextBuild#38]
Using the VersionAPPX task I can set the version in the manifest, but I need that number in the next task.

Would be cool to set an environment variable with the $NewVersion

**Comment by rfennell** [comment]
A reasonable enhancement, but as an interim measure I just make sure the buildnumber parameter I am passing in is in the right numeric format so I can you that in pother tasks, but I realise that might not work for you

**Comment by ridomin** [comment]
This will work, I just need the versionnumber to be figure out the complete file name of one of the generated artifacts.

**Comment by Mertsch** [comment]
This would be a great enhancement, just have a read-operation, to label your artifacts. I am looking exactly for that right now.

**Comment by rfennell** [comment]
Shipped in version 1.8

**Comment by Mertsch** [comment]
@rfennell Do you have any intention to also add a build task that just extracts the version number from an `AssemblyInfo.cs`?

**Comment by rfennell** [comment]
I don't, the reason is that I see this extension containing set of tasks as providing the means to stamp a version onto a package/assembly i.e. a write operation. 

Anything else would be a different extension in my view

**Comment by Mertsch** [comment]
@rfennell Thank you for this information.
