### ISSUE TITLE
Nuspec versioning fails if nuspec file is xml namespaced

### ISSUE THREAD

**Issue by richardjharding** [rfennell/vNextBuild#40]
I ran into an issue with the nuspec versioning task - it was failing with the following

`System.Management.Automation.RuntimeException: The property 'InnerText' cannot be found on this object. Verify that the property exists and can be set.`

I tracked this down to this line

`$xml.SelectSingleNode("/package/metadata/version").InnerText = $NewVersion`

It turned out that my nuspec file had an xml namespace declaration

`<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">`

which causes the call to SelectSingleNode to fail - I resolved it by removing the namespace declaration from my nuspec file

Not sure that this is a simple fix - apart from adding either name space param or nuspec schema version (which would translate to ns) - some discussion here [nuspec schema](http://stackoverflow.com/questions/33225461/how-to-specify-nuget-schema)

that's the only hiccup I had - otherwise these tasks have enable me to delete a lot of ps scripts scattered throughout projects ! - nice work

**Comment by rfennell** [comment]
I need to look if I can come up with some more prescriptive xpath to avoid the clash.
Thanks for point this out

**Comment by rfennell** [comment]
Altered the xpath query to account for the namespace 
In version 1.7.3 of the extension
