### ISSUE TITLE
Pester Runner in Azure PowerShell

### ISSUE THREAD

**Issue by DanielLarsenNZ** [rfennell/vNextBuild#42]
@rfennell - this is a great VSTS Task - I have been using it loads. Thank you. I have an enhancement request. I am using it more and more for Integration tests, Smoke tests (post-release, as part of a VSTS Release Configuration), that sort of thing. I am finding that I want to run AzureRM cmdlets in my tests but of course I need to `Login-AzureRMAccount`. I was wondering if it would be possible to have an "Azure PowerShell" version of the Task (if you know what I mean) or if you could propose a workaround.
Thanks in advance.

**Comment by rfennell** [comment]
How did you envision it working?

If I add a couple of extra parameters and logic similar to the following

```
param
(
$azureAccountName ,
$azurePassword 
)
$psCred = New-Object System.Management.Automation.PSCredential($azureAccountName, (ConvertTo-SecureString $azurePassword  -AsPlainText -Force))
Login-AzureRmAccount -Credential $psCred
// then the pester logic we have
```

would that work for what you envisage?
Basically adding the login call if the parameters are provided

**Comment by DanielLarsenNZ** [comment]
Would that allow me to use an (AAD Application) Service Principal? If so, great! I will do some research on the Azure PowerShell (builtin) task and see what their logic is...

**Comment by rfennell** [comment]
let me know what you discover, I think I would prefer to add a flag/switch to enable the extra function. but not against a second version of the task

**Comment by DanielLarsenNZ** [comment]
The Azure PowerShell task requires an input of type [`connectedService:AzureRM`](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzurePowerShell/task.json#L50)

`AzurePowerShell.ps1` then runs [`Initialize-Azure`](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzurePowerShell/AzurePowerShell.ps1#L20) which in turn calls [Initialize-AzureSubscription ](https://github.com/Microsoft/vsts-tasks/blob/396df52b6b99dfdbb2d247b238c044278b08a72d/Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1#L109). It _appears_ that the Endpoint knows the `ServicePrincipalId` and the `ServicePrincipalKey` and so can create the PSCreds for the Principal.

I wonder if [`Tasks/Common/VstsAzureHelpers_`](https://github.com/Microsoft/vsts-tasks/tree/396df52b6b99dfdbb2d247b238c044278b08a72d/Tasks/Common/VstsAzureHelpers_) are available to all tasks, or if they would need to be shipped with the Task?

@ericsciple, @pragupta-ms - care to comment?

**Comment by ericsciple** [comment]
you would need to copy the code and bundle it with your task. the build process in the vsts-tasks repo copies it into place for the tasks that consume it.

**Comment by rfennell** [comment]
My concern of bundling is the overhead it cause to make sure any modules are kept up to date. That said should like there is an outline idea here.

I will try to have a look to see what can be done, but not sure how quickly as I am going to be offline for a few weeks on holiday, going to be November at the soonest.

Happy to look at Pull Request submissions though

**Comment by DanielLarsenNZ** [comment]
@rfennell yes, I agree. I was hoping it would be an easy addition but I don't think it is worth the effort right now. Also, I am assuming that Pester will be installed software on Hosted Build Agents when they are upgraded to Windows 2016? I am not sure what the timeline for this is though.

If I get stuck and really need the feature I would be happy to Submit a PR :)

Thanks again.
