### ISSUE TITLE
Assembly Versions - allow separate versions for various Assembly versions

### ISSUE THREAD

**Issue by rfennell** [rfennell/vNextBuild#44]
Add support for setting each of the assembly versions independently
- AssemblyVersion 
- AssemlyFileVersion 
- AssemblyInformation.

**Comment by jzserai** [comment]
I agree that is an excellent approach. 

Looking forward to seeing it.

Thank you

**Comment by rfennell** [comment]
Shipped for all versioning tasks in 1.8.x

**Comment by rfennell** [comment]
Sorry closed in error, this is being added for version 1.9

**Comment by rfennell** [comment]
This feature has been released in 1.9.x

It has been done by adding an extra field on the Advanced where you can specify the version field to update. If this new parameter field is left empty (the default) the behaviour is as it has been in the past i.e. all version fields are updated.  

This means if you want to specify different values for different field you need to add multiple instances of the task to the build.
