### ISSUE TITLE
Get Artifact from UNC share issue

### ISSUE THREAD

**Issue by hsommer** [rfennell/vNextBuild#51]
Hi,
I am using VSTS and would like to try copying build artifacts from one build definition to another.
I get the following error message:
Getting lastest completed build
Microsoft.PowerShell.Commands.WriteErrorException: Cannot access source path [#/475339/artifact]
Processed: ##vso[task.logissue type=error;]Microsoft.PowerShell.Commands.WriteErrorException: Cannot access source path [#/475339/atrifact]
PowerShell script completed with 1 errors.
I can see that the artifact that should be picked is the one from the other build definition. So they are correctly related.

**Comment by rfennell** [comment]
This task is only designed to get build artifacts from a UNC drop e.g. //server/drop/build123 

You error **Cannot access source path [#/475339/atrifact]** suggest your build is storing its artifacts on the server. 

Can you confirm if this is the case

**Comment by hsommer** [comment]
You are right, I try to reference the server artifacts. Wasn't aware this could be a problem. Could probably an interesting feature for this extension. I wonder MS themselves are not offering this feature. 
Thanks for your reply.

**Comment by rfennell** [comment]
I considered making it an enhancement, but the name of the task does mention UNC paths, so on consideration I think I would write a new task that does both type of build drop. So not enhancing this one.

I will update the documentation to reflect the current functionality
