### ISSUE TITLE
VersionAssembly using PS environment encoding not file encoding

### ISSUE THREAD

**Issue by ChrisLGardner** [rfennell/vNextBuild#53]
I've ran into an issue where the AssemblyInfo.cs file was encoded with UTF-8 but the build agent was running in UTF-16 LE (for some reason). This meant that when the version was update and written back to the file it was now in UTF-16 LE encoding. 

Not a problem for MSBuild to handle properly but SonarQube was falling over as it was expecting UTF-8, which all the other files were in. 

A suggested fix is to get the encoding of the file before reading it in and then specify that same encoding when using Out-File. I've got the fix for this already written and will put in the pull request soon containing it.

**Comment by rfennell** [comment]
Fixed and released using @ChrisLGardner  code
