### ISSUE TITLE
Release Notes Cannot access the build parameters using a template

### ISSUE THREAD

**Issue by rfennell** [rfennell/vNextBuild#55]
_This issues as been created to provide a record of Twitter conversation_

You usually access the properties of a build in a templates as follows

`**Build Number**  : $($build.buildnumber) 
`

You would expect to be able to access inner properties in the following manner

`**Build Config**  : $($build.parameters.BuildConfiguration) 
`

But this does not work

**Comment by rfennell** [comment]
The issue is that if you return

`$build.parameters
`

you find it is a string of json data e.g

`{"system.debug":"false","BuildConfiguration":"release","BuildPlatform":"any cpu"}
`

You need to parse this again, so the line to get the inner property is

`**Build Config**  : $($build.parameters | ConvertFrom-Json | select -ExpandProperty BuildConfiguration )
`

**Comment by cmoye** [comment]
rfennell how do I update this in my inline template?
