### ISSUE TITLE
Manifest Versioning Build Tasks support for Xamarin Android/iOS

### ISSUE THREAD

**Issue by jerone** [rfennell/vNextBuild#62]
I couldn't find any reference on using this with Xamarin Android and/or iOS. 
Is this supported or are you interested in adding support for it?

**Comment by insanity13** [comment]
@jerone, we using this great task in our Xamarin projects. 
Android builds on Windows machine and release notes generates in Build Definition.
iOS builds on Mac and this task is not supported on it, so we put generating ReleaseNotes in Release Management which builds on Windows.

**Comment by jerone** [comment]
> Which extension were you thinking of?

Oh sorry, I came here for _Manifest Versioning Build Tasks_ from the Marketplace. Didn't expect this repo to contain more then one extension.

**Comment by rfennell** [comment]
With hindsight having a single repo might not have been the best idea, but I think I a bit late to change it now, we live and learn. never expect to be producing so many extensions.

The ask for the versioning on Xplat is reasonable, just not sure how fast I will get around to it. Our Xamarin work is on Android so we can build on Windows.

So I have labelled the issue as an enhancement and as help wanted, happy to look at pull requests.

**Comment by dwhathaway** [comment]
@insanity13 would you be able to share the configuration you used for the Release Definition?  I'm trying to set up the same thing in a hosted VSTS instance (with a Hosted Windows build agent), and I'm getting the following error when I run the release deployment.

> ##[error]System.Management.Automation.PSArgumentException: Property "BuildConfiguration" cannot be found.

**Comment by dwhathaway** [comment]
@insanity13 please disregard.  I figured out that I was using a [Build template,](https://github.com/rfennell/vNextBuild/blob/master/SampleTemplates/build-basic-template.md) rather than a [release template](https://github.com/rfennell/vNextBuild/blob/master/SampleTemplates/release-basic-template.md), so some of the variables weren't defined.  When I change the template, it worked as expected.

**Comment by rfennell** [comment]
Glad you got sorted

**Comment by rfennell** [comment]
This is currently being worked on to add Node support for assemby versioning

**Comment by rfennell** [comment]
Shipped in 1.5.22 as a new task to version .NETCore that works cross platform
