### ISSUE TITLE
Allow for Files to be Named Something Other than assemblyinfo.*

### ISSUE THREAD

**Issue by james-h-stephens** [rfennell/vNextBuild#65]
### VSTS Extension you are using
VersionAssemblies 

### Expected behavior and actual behavior
Allow for files to be named something other than assemblyinfo.*

**Comment by rfennell** [comment]
I can certainly make the file name a property you can override, but the regex that does the match is specfic to the assemble.* format. is that going to be an issue for your scenario?

**Comment by rfennell** [comment]
Just hit the same requirement myself, a client had a sharedassemblyinfo.cs file
I have added the option as a parameter in 1.11.x
