### ISSUE TITLE
Assemby- and Manifest-Versioning with Changeset-ID

### ISSUE THREAD

**Issue by volkhardv** [rfennell/vNextBuild#68]
### VSTS Extension you are using
Version Assemblies, Version APPX
### Expected behavior and actual behavior
Hello, 
i would like to patch the last number in der Versions of AssembliesInfo.cs and Appx-Manifests with the changeset id. How can i do this with your components on TFS 2017?

best regards

**Comment by rfennell** [comment]
There is a build variable $(build.buildnumber) that contains the value you are after. It is listed with the other built in variables on [MSDN](https://www.visualstudio.com/en-us/docs/build/define/variables)

There are many options to use this variable, but you could use it in the build number as follows

```
$(major).$(minor).$(year:yy)$(dayofyear).$(Build.SOURCEVERSION)
```

Where Major and Minor are user defined variables, and the third block is the day of the year.

This should work as long as your changesetID is under around 32000, as as I remember this the max for any number in any part of an assembly versions

**Comment by rfennell** [comment]
As is my usual practice, I will close this call in a 7 days when I think it is resolve. You can of course re-open it if there is still an issue
