### ISSUE TITLE
Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (401) Unauthorized."

### ISSUE THREAD

**Issue by yermax** [rfennell/vNextBuild#70]
### VSTS Extension you are using
2.2.1

### Expected behavior and actual behavior
should use default credentials to retrieve data, but it does not. instead it uses tokens

### Steps to reproduce the problem
on premises tfs 2015.2.
use default credentials

**Comment by yermax** [comment]
Fixed the issue. Some of the calls of Get-Details function are missing " -usedefaultcreds $usedefaultcreds" argument

Get-Detail -uri $wi.url
instead of
**Get-Detail -uri $wi.url -usedefaultcreds $usedefaultcreds**

**Comment by rfennell** [comment]
Ops, I will get that fixed, which of the various Extensions in this repo are you using?
Or send a pull request

**Comment by yermax** [comment]
I'm using GenerateReleaseNotes

**Comment by rfennell** [comment]
The pull request #71 has been merged. 

I am holding off on a release to the marketplace as I want to have a quick look at #69 and get the fix rolled into the next release 2.3.x
