### ISSUE TITLE
Trap 404 errors if an artifact cannot be found when generating release notes

### ISSUE THREAD

**Issue by rfennell** [rfennell/vNextBuild#72]
### VSTS Extension you are using
GenerateRelease notes

@gigeld asked in #34 - decided it needed its own issue

Any luck with trapping that 404 error? In our pipelines is thrown when some builds have been deleted (usually by the retention policy). The Generate Release Notes task will still list all the Work Items found in the available builds but because of the 404 errors,, the task will display in red, as 'Failed'.
Maybe just a warning message would be a better option than 404 error. Thanks!

**Comment by rfennell** [comment]
@gregpakes and @gigeld Added a try catch around both the get work items and get changesets/commits, this traps any error and writes a warnings.

It has just shipped as 2.4.2

Let me know if it sort your problems

**Comment by gregpakes** [comment]
Looks good to me

**Comment by rfennell** [comment]
I'll call that resolved then

**Comment by gigeld** [comment]
Thanks again for your great support!
