### ISSUE TITLE
Enhancement request - hide empty commits

### ISSUE THREAD

**Issue by Beej126** [rfennell/vNextBuild#75]
### VSTS Extension you are using
Generate Release Notes

### Where are you running it?
VSTS

### Expected behavior and actual behavior
Two small enhancement requests:
1) Don't show the "Work Item" header if there aren't any 
2) Don't show individual commits if the message property is empty

motivations
1) In one of my smaller projects the releases are typically just commits w/o any work items so it would be cleaner if it wouldn't show at all... but sometimes there are work items so i don't want to remove that loop entirely from my template

2) sometimes i'll just forget to check something in so i'll have an immediate followup commit that i'd simply like to leave blank and not show up at all

**Comment by rfennell** [comment]
The issue with this enhancement request is that each line of the template is evaluated line by line to be rendered; so via the code there is currently no simple way to look ahead to see what the next template line might do.

There is a detailed discussion of the processing issue this raised by adding this type of evaluate of lines of powershell as opposed to just rendering out values (see issue #35), the summary is adding evaluation would add security issues.
