### ISSUE TITLE
Cannot bind argument to parameter 'Message' because it is null.

### ISSUE THREAD

**Issue by aharmer76** [rfennell/vNextBuild#76]
Generate Release Notes Build Task v2.5.1
on-premise TFS (2017)

### Expected behavior and actual behavior
Build task fails with:

System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.
PowerShell script completed with 2 errors.

### Steps to reproduce the problem
Template file:

[ReleaseNotesTemplate.zip]
![buildtask](https://cloud.githubusercontent.com/assets/25930533/23169280/122a8a6a-f843-11e6-8083-15d06e640aa7.PNG)
(https://github.com/rfennell/vNextBuild/files/790404/ReleaseNotesTemplate.zip)

**Comment by rfennell** [comment]
This error usually occurs when you are trying to use a non-existant field, property or construct in the template.

1. I notice your template is for a release (as opposed to a build) is this correct? There are no release based values available for a build.
2. Have you tried with one of the sample templates for markdown (either build or release based as needed)
3. What output do you see generated, this can give an idea of the line of the template that is failing

**Comment by aharmer76** [comment]
Your right, my bad, tried with the build template and all works.

**Comment by rfennell** [comment]
Easy mistake to make, I do it all the time, glad you are working now
