### ISSUE TITLE
Pester: Support Tag and ExcludeTag parameters

### ISSUE THREAD

**Issue by ChrisLGardner** [rfennell/vNextBuild#77]
Adding support for the Tag and ExcludeTag parameters on Invoke-Pester.

Also adding some extra checking for if Pester is already installed and to default to that if it's available.

**Comment by rfennell** [comment]
Turns out there was an issue with the validation build in VSTS, this was because the modulefolder param is optional it causes a failure when it used within a VSTS build as a null is passed into ValidateScript. Needed an extra check for this, which has been added

Release in 4.3.4
