### ISSUE TITLE
LoadFromDacpac error loading Sql130DatabaseSchemaProvider

### ISSUE THREAD

**Issue by rfennell** [rfennell/vNextBuild#86]
### VSTS Extension you are using
DACPac Versioning 

### Where are you running it?
User reported, did not state which

### Version of Extension/Task
1.12.5

### Expected behavior and actual behavior
User review reported error -  I got the following error for versioning DACPACs:

`
System.Management.Automation.MethodInvocationException: Exception calling "LoadFromDacpac" with "2" argument(s): "Could not load schema model from package." ---> Microsoft.SqlServer.Dac.DacServicesException: Could not load schema model from package. ---> Microsoft.Data.Tools.Schema.Extensibility.ExtensibilityException: Internal Error. The database platform service with type Microsoft.Data.Tools.Schema.Sql.Sql130DatabaseSchemaProvider is not valid. You must make sure the service is loaded, or you must provide the full type name of a valid database platform service.
`
### Steps to reproduce the problem
Try to use the task withouth the 130 version (SQL2016) DAC tools installed

**Comment by rfennell** [comment]
I looked into this and the problem is the task only looks for DLLs in the 120 sub folders. You could get around this by passing a in a fixed toolpath, but it does need to be fixed.

I have taken the chance to add support for the 130 folders and the default paths for VS2017

**Comment by rfennell** [comment]
Fix released as 1.1.3x

Leaving issue open until get confirmation fixes end user issue

**Comment by eduardomhg** [comment]
I have already tested it with my DACPACs and seems to work fine! Thanks a lot for the quick response and release. I will update my review at the Marketplace along with some other improvements I would like to propose.

**Comment by rfennell** [comment]
@eduardomhg great news, if you have enhancement ideas it would be great if you could add them as issue here on GitHub, they are easier to track

**Comment by nagisetty1** [comment]
try below steps,

The version number 130 in error message belongs to SQL Server 2016, and the database where I need to deploy DACPAC was SQL Server 2012/2014. So, its clear that the DACPAC was built in Visual Studio with SQL Server 2016 setting.

SO go to Visual Studio open database project and select Properties-->Project Settings and change the version to SQL Server 2012/2014, and re-build the Project, and got the correct DACPAC file.
