### ISSUE TITLE
Make the GenerateReleaseNotes task for on non-Windows agents

### ISSUE THREAD

**Issue by rfennell** [rfennell/vNextBuild#9]
This will require migrating to Node/Javascript. This should not be a major issue for the REST based business logic, but how do we write the template?

Currently the template is in effect markdown with embedded PowerShell, could we use the same model or will be need Node specific templates?

**Comment by kacperryniec** [comment]
That would be absolutely awesome! Especially nowadays when Xamarin is becoming more and more popular and VSTO is strongly supporting non-windows builds via for example OS X agents.

**Comment by rfennell** [comment]
Have a look at my nww`[crossplatform extension](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes).

See [this blog post](http://blogs.blackmarble.co.uk/blogs/rfennell/post/2017/04/12/New-Cross-Platform-version-of-my-Generate-Release-Notes-VSTS-Extension) for background
