### ISSUE TITLE
Update Build Variable Task fails for Primary Artifacts Only mode

### ISSUE THREAD

**Issue by SchulzDL** [rfennell/vNextBuild#90]
### VSTS Extension you are using
Update Build Variable Task

### Where are you running it?
VSTS

### Version of Extension/Task
currently public version

### Expected behavior and actual behavior
Getting all kinds of errors which starts with a can't convert to Boolean "1" which continues to spiral into more errors and then finally just fails.  Of course I am expecting the variable to increment like it always has done in the past.  However I noticed a change that was implemented about 5 or 6 days ago and investigated the changes.

### Steps to reproduce the problem
If you use the Primary Artifacts instead of All Artifacts you get it series of errors.  It turns out it does not if you go through the All Artifacts.  It turns out that in the PowerShell script where you are passing in a named variable you left the $ on the named variable which I noticed did not have this in the All Artifacts route.  This is near the end of the script where it calls the Update-Build function for the usedefaultcredentials parameter.

**Comment by rfennell** [comment]
I am looking into it now, it appears that for people using the older version of the task the default value for a new parameter is set.

**Comment by rfennell** [comment]
Firstly @SchulzDL thanks for the really good repo instructions. I have added extra tests to my release pipeline to make sure both the all artifacts and primary artifacts are properly tested.

The fix has now been released as 1.3.x
