### ISSUE TITLE
List parent work items for tasks

### ISSUE THREAD

**Issue by SWarnberg** [rfennell/vNextBuild#92]
### Generate Release Notes Build Task
*On-premise TFS (2.5.1)*

### Enhancement suggestion
A high-rated suggestion on uservoice is to associate parent work items with the builds. However, it still hasn't been implemented by MS, even though it should be simple. Normally, for new functions you're only interested in the PBI/User Story and not the Tasks when you write release notes.

Would be great if this task could do that job. Also, Another connected suggestion is to give the ability to filter the ouput of work item types. For instance, I just want to list the User Stories and Bugs associated with the build/release.

**Comment by rfennell** [comment]
The first one is reasonable, it is possible to walk up the work item relationships, so it goes on the backlog, not sure when I will get to it

The second point is more awkward, there are a few similar requests to add filtering/logic to the task. The reason this has not been done for security reasons we do not want to be executing random powershell. So for now I will not be considering adding that.

Of course happy to accept PRs if some adds and enhancement

**Comment by SWarnberg** [comment]
Great, looking forward to it.

About the second point; wouldn't it be easy to have an argument in the task for the filter and then a simple switch statement in the foreach loop in Get-BuildWorkItems?
I may have a look at this some time myself. To me it's quite important to get rid of the _Code Review Request_ WI's, for instance.

**Comment by rfennell** [comment]
@SWarnberg yes some sort of toggle in the task properties and some logic in the Get-BuildWorkItems would work. However my concern is that I am imposing a way of working on the end user, up to now I have tried to make the tasks as generic as possible, putting decisions on the template, with the limitations that imposes. May time to change this style?

**Comment by rfennell** [comment]
Added the help wanted label as I doubt I will have time to look at this, but happy to accept PRs

**Comment by SWarnberg** [comment]
I just added a PR on above suggestion. Included parent WI as well as filtering option.
I've tested it on Builds, but not yet on Releases, but it should work.

**Comment by rfennell** [comment]
Adding the contents of the PR #221 - also including some other enhancements, should be released early in the new year

**Comment by rfennell** [comment]
Shipped as 2.12.5
