### ISSUE TITLE
too many WorkItems and changes on release notes

### ISSUE THREAD

**Issue by alfhv** [rfennell/vNextBuild#99]
### VSTS Extension you are using
Create-ReleaseNotes.ps1

### Where are you running it?
on-premise TFS 2015

### Version of Extension/Task
I have downloaded Create-ReleaseNotes.ps1 and VSTSPowershell/REST/template.md files. Both are locally on my TFS Agent (on-premises)

### Expected behavior and actual behavior
WorkItems and change items on release notes are too many.
On TFS/Release/Commits and TFS/Release/WorkItems sections I have just a few, the good list of them.

please give me some advice how wotkitem and chages content is calculated by the script different than the TFS itself.

thanks a lot

**Comment by rfennell** [comment]
Using the REST API we either
- find the build - if the task is being using in a build
- find the release, and all the included builds since the last successful release to the same environment  - if using the task in a release

We then loop through the list of builds and get the wi and commits details, these are then added to the notes document.

**Comment by alfhv** [comment]
I see the issue I 'm having...
I'm using the task on a Release and the wi and commits generated are taken from the Build details result screen and not from the Release.
On the Release screen, wi and commits are calculated by TFS (as far as I know) related to the previous release, and this is what I want.

the arguments I'm passing to ps1 script is:

-collectionUrl http://mytfs.onpremises/MyCollection -teamproject "MyTeamProject" –defname "MyBuildDefinitionName" -outputfile "releasenotes.md" -templatefile "MyPath\template.md" -buildnumber "$(Build.BuildNumber)"

my BuildVersion at Release execution time is: 3.0.6.10
my ReleaseNames at execution time is: Release-3.0.6.10 (and previous release name is Release-3.0.6.09)

Is there any way to make the script calculate wi and commits like TFS, based on previous Release ? any issue on my params ?

thanks

**Comment by rfennell** [comment]
Funny you should ask that, I have been playing around ideas in this area, using the unpublished RM REST API calls the UI uses.

It is far from ready as yet, but i have create a issue #100 to track it

**Comment by rfennell** [comment]
Closing this issue as I am tracking the development of the new task in #100
